version: '3.8'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.prod
    container_name: wep_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - wep_network
