"""add matching fileupload support

Revision ID: 8eb66aa027fe
Revises: d82fa57d2ce6
Create Date: 2026-05-18 12:46:31.945303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eb66aa027fe'
down_revision: Union[str, Sequence[str], None] = 'd82fa57d2ce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('matching_answer', sa.JSON(), nullable=True))
    op.add_column('answers', sa.Column('file_answer', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('question_data', sa.JSON(), nullable=True))
    op.add_column('tests', sa.Column('image_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'image_url')
    op.drop_column('questions', 'question_data')
    op.drop_column('answers', 'file_answer')
    op.drop_column('answers', 'matching_answer')
    # ### end Alembic commands ###
