"""make attempt unique constraint partial for in_progress

Revision ID: 5351ba4fda5d
Revises: 8eb66aa027fe
Create Date: 2026-05-18 16:12:23.078770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5351ba4fda5d'
down_revision: Union[str, Sequence[str], None] = '8eb66aa027fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_test_active_attempt'), 'attempts', type_='unique')
    op.create_index('uq_user_test_active_attempt', 'attempts', ['user_id', 'test_id'], unique=True, postgresql_where=sa.text("status = 'in_progress'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_user_test_active_attempt', table_name='attempts', postgresql_where=sa.text("status = 'in_progress'"))
    op.create_unique_constraint(op.f('uq_user_test_active_attempt'), 'attempts', ['user_id', 'test_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
