/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Test Constructor API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AnswerResponse,
  AnswerSubmitRequest,
  AttemptResponse,
  AttemptResultResponse,
  AttemptStartRequest,
  ErrorResponse,
  HTTPValidationError
} from './testConstructorAPI.schemas';

import { request } from '../axios';





export type startAttemptApiV1AttemptsPostResponse201 = {
  data: AttemptResponse
  status: 201
}

export type startAttemptApiV1AttemptsPostResponse400 = {
  data: ErrorResponse
  status: 400
}

export type startAttemptApiV1AttemptsPostResponse401 = {
  data: ErrorResponse
  status: 401
}

export type startAttemptApiV1AttemptsPostResponse403 = {
  data: ErrorResponse
  status: 403
}

export type startAttemptApiV1AttemptsPostResponse404 = {
  data: ErrorResponse
  status: 404
}

export type startAttemptApiV1AttemptsPostResponse409 = {
  data: ErrorResponse
  status: 409
}

export type startAttemptApiV1AttemptsPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type startAttemptApiV1AttemptsPostResponse500 = {
  data: ErrorResponse
  status: 500
}

export type startAttemptApiV1AttemptsPostResponseSuccess = (startAttemptApiV1AttemptsPostResponse201) & {
  headers: Headers;
};
export type startAttemptApiV1AttemptsPostResponseError = (startAttemptApiV1AttemptsPostResponse400 | startAttemptApiV1AttemptsPostResponse401 | startAttemptApiV1AttemptsPostResponse403 | startAttemptApiV1AttemptsPostResponse404 | startAttemptApiV1AttemptsPostResponse409 | startAttemptApiV1AttemptsPostResponse422 | startAttemptApiV1AttemptsPostResponse500) & {
  headers: Headers;
};

export type startAttemptApiV1AttemptsPostResponse = (startAttemptApiV1AttemptsPostResponseSuccess | startAttemptApiV1AttemptsPostResponseError)

export const getStartAttemptApiV1AttemptsPostUrl = () => {




  return `/api/v1/attempts/`
}

/**
 * @summary Start Attempt
 */
export const startAttemptApiV1AttemptsPost = async (attemptStartRequest: AttemptStartRequest, options?: RequestInit): Promise<startAttemptApiV1AttemptsPostResponse> => {

  return request<startAttemptApiV1AttemptsPostResponse>(getStartAttemptApiV1AttemptsPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(attemptStartRequest)
  }
);}





export const getStartAttemptApiV1AttemptsPostQueryKey = (attemptStartRequest?: AttemptStartRequest,) => {
    return [
    'POST', `/api/v1/attempts/`, attemptStartRequest
    ] as const;
    }


export const getStartAttemptApiV1AttemptsPostQueryOptions = <TData = Awaited<ReturnType<typeof startAttemptApiV1AttemptsPost>>, TError = ErrorResponse | HTTPValidationError>(attemptStartRequest: AttemptStartRequest, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof startAttemptApiV1AttemptsPost>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStartAttemptApiV1AttemptsPostQueryKey(attemptStartRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof startAttemptApiV1AttemptsPost>>> = ({ signal }) => startAttemptApiV1AttemptsPost(attemptStartRequest, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof startAttemptApiV1AttemptsPost>>, TError, TData> & { queryKey: QueryKey }
}

export type StartAttemptApiV1AttemptsPostQueryResult = NonNullable<Awaited<ReturnType<typeof startAttemptApiV1AttemptsPost>>>
export type StartAttemptApiV1AttemptsPostQueryError = ErrorResponse | HTTPValidationError


/**
 * @summary Start Attempt
 */

export function useStartAttemptApiV1AttemptsPost<TData = Awaited<ReturnType<typeof startAttemptApiV1AttemptsPost>>, TError = ErrorResponse | HTTPValidationError>(
 attemptStartRequest: AttemptStartRequest, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof startAttemptApiV1AttemptsPost>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getStartAttemptApiV1AttemptsPostQueryOptions(attemptStartRequest,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type getAttemptApiV1AttemptsAttemptIdGetResponse200 = {
  data: AttemptResponse
  status: 200
}

export type getAttemptApiV1AttemptsAttemptIdGetResponse400 = {
  data: ErrorResponse
  status: 400
}

export type getAttemptApiV1AttemptsAttemptIdGetResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getAttemptApiV1AttemptsAttemptIdGetResponse403 = {
  data: ErrorResponse
  status: 403
}

export type getAttemptApiV1AttemptsAttemptIdGetResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getAttemptApiV1AttemptsAttemptIdGetResponse409 = {
  data: ErrorResponse
  status: 409
}

export type getAttemptApiV1AttemptsAttemptIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getAttemptApiV1AttemptsAttemptIdGetResponse500 = {
  data: ErrorResponse
  status: 500
}

export type getAttemptApiV1AttemptsAttemptIdGetResponseSuccess = (getAttemptApiV1AttemptsAttemptIdGetResponse200) & {
  headers: Headers;
};
export type getAttemptApiV1AttemptsAttemptIdGetResponseError = (getAttemptApiV1AttemptsAttemptIdGetResponse400 | getAttemptApiV1AttemptsAttemptIdGetResponse401 | getAttemptApiV1AttemptsAttemptIdGetResponse403 | getAttemptApiV1AttemptsAttemptIdGetResponse404 | getAttemptApiV1AttemptsAttemptIdGetResponse409 | getAttemptApiV1AttemptsAttemptIdGetResponse422 | getAttemptApiV1AttemptsAttemptIdGetResponse500) & {
  headers: Headers;
};

export type getAttemptApiV1AttemptsAttemptIdGetResponse = (getAttemptApiV1AttemptsAttemptIdGetResponseSuccess | getAttemptApiV1AttemptsAttemptIdGetResponseError)

export const getGetAttemptApiV1AttemptsAttemptIdGetUrl = (attemptId: number,) => {




  return `/api/v1/attempts/${attemptId}`
}

/**
 * @summary Get Attempt
 */
export const getAttemptApiV1AttemptsAttemptIdGet = async (attemptId: number, options?: RequestInit): Promise<getAttemptApiV1AttemptsAttemptIdGetResponse> => {

  return request<getAttemptApiV1AttemptsAttemptIdGetResponse>(getGetAttemptApiV1AttemptsAttemptIdGetUrl(attemptId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAttemptApiV1AttemptsAttemptIdGetQueryKey = (attemptId: number,) => {
    return [
    `/api/v1/attempts/${attemptId}`
    ] as const;
    }


export const getGetAttemptApiV1AttemptsAttemptIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getAttemptApiV1AttemptsAttemptIdGet>>, TError = ErrorResponse | HTTPValidationError>(attemptId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAttemptApiV1AttemptsAttemptIdGet>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAttemptApiV1AttemptsAttemptIdGetQueryKey(attemptId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAttemptApiV1AttemptsAttemptIdGet>>> = ({ signal }) => getAttemptApiV1AttemptsAttemptIdGet(attemptId, { signal });





   return  { queryKey, queryFn, enabled: attemptId !== null && attemptId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAttemptApiV1AttemptsAttemptIdGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAttemptApiV1AttemptsAttemptIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getAttemptApiV1AttemptsAttemptIdGet>>>
export type GetAttemptApiV1AttemptsAttemptIdGetQueryError = ErrorResponse | HTTPValidationError


/**
 * @summary Get Attempt
 */

export function useGetAttemptApiV1AttemptsAttemptIdGet<TData = Awaited<ReturnType<typeof getAttemptApiV1AttemptsAttemptIdGet>>, TError = ErrorResponse | HTTPValidationError>(
 attemptId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAttemptApiV1AttemptsAttemptIdGet>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAttemptApiV1AttemptsAttemptIdGetQueryOptions(attemptId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type submitAnswerApiV1AttemptsAttemptIdAnswersPostResponse200 = {
  data: AnswerResponse
  status: 200
}

export type submitAnswerApiV1AttemptsAttemptIdAnswersPostResponse400 = {
  data: ErrorResponse
  status: 400
}

export type submitAnswerApiV1AttemptsAttemptIdAnswersPostResponse401 = {
  data: ErrorResponse
  status: 401
}

export type submitAnswerApiV1AttemptsAttemptIdAnswersPostResponse403 = {
  data: ErrorResponse
  status: 403
}

export type submitAnswerApiV1AttemptsAttemptIdAnswersPostResponse404 = {
  data: ErrorResponse
  status: 404
}

export type submitAnswerApiV1AttemptsAttemptIdAnswersPostResponse409 = {
  data: ErrorResponse
  status: 409
}

export type submitAnswerApiV1AttemptsAttemptIdAnswersPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type submitAnswerApiV1AttemptsAttemptIdAnswersPostResponse500 = {
  data: ErrorResponse
  status: 500
}

export type submitAnswerApiV1AttemptsAttemptIdAnswersPostResponseSuccess = (submitAnswerApiV1AttemptsAttemptIdAnswersPostResponse200) & {
  headers: Headers;
};
export type submitAnswerApiV1AttemptsAttemptIdAnswersPostResponseError = (submitAnswerApiV1AttemptsAttemptIdAnswersPostResponse400 | submitAnswerApiV1AttemptsAttemptIdAnswersPostResponse401 | submitAnswerApiV1AttemptsAttemptIdAnswersPostResponse403 | submitAnswerApiV1AttemptsAttemptIdAnswersPostResponse404 | submitAnswerApiV1AttemptsAttemptIdAnswersPostResponse409 | submitAnswerApiV1AttemptsAttemptIdAnswersPostResponse422 | submitAnswerApiV1AttemptsAttemptIdAnswersPostResponse500) & {
  headers: Headers;
};

export type submitAnswerApiV1AttemptsAttemptIdAnswersPostResponse = (submitAnswerApiV1AttemptsAttemptIdAnswersPostResponseSuccess | submitAnswerApiV1AttemptsAttemptIdAnswersPostResponseError)

export const getSubmitAnswerApiV1AttemptsAttemptIdAnswersPostUrl = (attemptId: number,) => {




  return `/api/v1/attempts/${attemptId}/answers`
}

/**
 * @summary Submit Answer
 */
export const submitAnswerApiV1AttemptsAttemptIdAnswersPost = async (attemptId: number,
    answerSubmitRequest: AnswerSubmitRequest, options?: RequestInit): Promise<submitAnswerApiV1AttemptsAttemptIdAnswersPostResponse> => {

  return request<submitAnswerApiV1AttemptsAttemptIdAnswersPostResponse>(getSubmitAnswerApiV1AttemptsAttemptIdAnswersPostUrl(attemptId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(answerSubmitRequest)
  }
);}





export const getSubmitAnswerApiV1AttemptsAttemptIdAnswersPostQueryKey = (attemptId: number,
    answerSubmitRequest?: AnswerSubmitRequest,) => {
    return [
    'POST', `/api/v1/attempts/${attemptId}/answers`, answerSubmitRequest
    ] as const;
    }


export const getSubmitAnswerApiV1AttemptsAttemptIdAnswersPostQueryOptions = <TData = Awaited<ReturnType<typeof submitAnswerApiV1AttemptsAttemptIdAnswersPost>>, TError = ErrorResponse | HTTPValidationError>(attemptId: number,
    answerSubmitRequest: AnswerSubmitRequest, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof submitAnswerApiV1AttemptsAttemptIdAnswersPost>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSubmitAnswerApiV1AttemptsAttemptIdAnswersPostQueryKey(attemptId,answerSubmitRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof submitAnswerApiV1AttemptsAttemptIdAnswersPost>>> = ({ signal }) => submitAnswerApiV1AttemptsAttemptIdAnswersPost(attemptId,answerSubmitRequest, { signal });





   return  { queryKey, queryFn, enabled: attemptId !== null && attemptId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof submitAnswerApiV1AttemptsAttemptIdAnswersPost>>, TError, TData> & { queryKey: QueryKey }
}

export type SubmitAnswerApiV1AttemptsAttemptIdAnswersPostQueryResult = NonNullable<Awaited<ReturnType<typeof submitAnswerApiV1AttemptsAttemptIdAnswersPost>>>
export type SubmitAnswerApiV1AttemptsAttemptIdAnswersPostQueryError = ErrorResponse | HTTPValidationError


/**
 * @summary Submit Answer
 */

export function useSubmitAnswerApiV1AttemptsAttemptIdAnswersPost<TData = Awaited<ReturnType<typeof submitAnswerApiV1AttemptsAttemptIdAnswersPost>>, TError = ErrorResponse | HTTPValidationError>(
 attemptId: number,
    answerSubmitRequest: AnswerSubmitRequest, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof submitAnswerApiV1AttemptsAttemptIdAnswersPost>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getSubmitAnswerApiV1AttemptsAttemptIdAnswersPostQueryOptions(attemptId,answerSubmitRequest,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type finishAttemptApiV1AttemptsAttemptIdFinishPostResponse200 = {
  data: AttemptResultResponse
  status: 200
}

export type finishAttemptApiV1AttemptsAttemptIdFinishPostResponse400 = {
  data: ErrorResponse
  status: 400
}

export type finishAttemptApiV1AttemptsAttemptIdFinishPostResponse401 = {
  data: ErrorResponse
  status: 401
}

export type finishAttemptApiV1AttemptsAttemptIdFinishPostResponse403 = {
  data: ErrorResponse
  status: 403
}

export type finishAttemptApiV1AttemptsAttemptIdFinishPostResponse404 = {
  data: ErrorResponse
  status: 404
}

export type finishAttemptApiV1AttemptsAttemptIdFinishPostResponse409 = {
  data: ErrorResponse
  status: 409
}

export type finishAttemptApiV1AttemptsAttemptIdFinishPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type finishAttemptApiV1AttemptsAttemptIdFinishPostResponse500 = {
  data: ErrorResponse
  status: 500
}

export type finishAttemptApiV1AttemptsAttemptIdFinishPostResponseSuccess = (finishAttemptApiV1AttemptsAttemptIdFinishPostResponse200) & {
  headers: Headers;
};
export type finishAttemptApiV1AttemptsAttemptIdFinishPostResponseError = (finishAttemptApiV1AttemptsAttemptIdFinishPostResponse400 | finishAttemptApiV1AttemptsAttemptIdFinishPostResponse401 | finishAttemptApiV1AttemptsAttemptIdFinishPostResponse403 | finishAttemptApiV1AttemptsAttemptIdFinishPostResponse404 | finishAttemptApiV1AttemptsAttemptIdFinishPostResponse409 | finishAttemptApiV1AttemptsAttemptIdFinishPostResponse422 | finishAttemptApiV1AttemptsAttemptIdFinishPostResponse500) & {
  headers: Headers;
};

export type finishAttemptApiV1AttemptsAttemptIdFinishPostResponse = (finishAttemptApiV1AttemptsAttemptIdFinishPostResponseSuccess | finishAttemptApiV1AttemptsAttemptIdFinishPostResponseError)

export const getFinishAttemptApiV1AttemptsAttemptIdFinishPostUrl = (attemptId: number,) => {




  return `/api/v1/attempts/${attemptId}/finish`
}

/**
 * @summary Finish Attempt
 */
export const finishAttemptApiV1AttemptsAttemptIdFinishPost = async (attemptId: number, options?: RequestInit): Promise<finishAttemptApiV1AttemptsAttemptIdFinishPostResponse> => {

  return request<finishAttemptApiV1AttemptsAttemptIdFinishPostResponse>(getFinishAttemptApiV1AttemptsAttemptIdFinishPostUrl(attemptId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getFinishAttemptApiV1AttemptsAttemptIdFinishPostQueryKey = (attemptId: number,) => {
    return [
    'POST', `/api/v1/attempts/${attemptId}/finish`
    ] as const;
    }


export const getFinishAttemptApiV1AttemptsAttemptIdFinishPostQueryOptions = <TData = Awaited<ReturnType<typeof finishAttemptApiV1AttemptsAttemptIdFinishPost>>, TError = ErrorResponse | HTTPValidationError>(attemptId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof finishAttemptApiV1AttemptsAttemptIdFinishPost>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFinishAttemptApiV1AttemptsAttemptIdFinishPostQueryKey(attemptId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof finishAttemptApiV1AttemptsAttemptIdFinishPost>>> = ({ signal }) => finishAttemptApiV1AttemptsAttemptIdFinishPost(attemptId, { signal });





   return  { queryKey, queryFn, enabled: attemptId !== null && attemptId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof finishAttemptApiV1AttemptsAttemptIdFinishPost>>, TError, TData> & { queryKey: QueryKey }
}

export type FinishAttemptApiV1AttemptsAttemptIdFinishPostQueryResult = NonNullable<Awaited<ReturnType<typeof finishAttemptApiV1AttemptsAttemptIdFinishPost>>>
export type FinishAttemptApiV1AttemptsAttemptIdFinishPostQueryError = ErrorResponse | HTTPValidationError


/**
 * @summary Finish Attempt
 */

export function useFinishAttemptApiV1AttemptsAttemptIdFinishPost<TData = Awaited<ReturnType<typeof finishAttemptApiV1AttemptsAttemptIdFinishPost>>, TError = ErrorResponse | HTTPValidationError>(
 attemptId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof finishAttemptApiV1AttemptsAttemptIdFinishPost>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getFinishAttemptApiV1AttemptsAttemptIdFinishPostQueryOptions(attemptId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type getResultApiV1AttemptsAttemptIdResultGetResponse200 = {
  data: AttemptResultResponse
  status: 200
}

export type getResultApiV1AttemptsAttemptIdResultGetResponse400 = {
  data: ErrorResponse
  status: 400
}

export type getResultApiV1AttemptsAttemptIdResultGetResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getResultApiV1AttemptsAttemptIdResultGetResponse403 = {
  data: ErrorResponse
  status: 403
}

export type getResultApiV1AttemptsAttemptIdResultGetResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getResultApiV1AttemptsAttemptIdResultGetResponse409 = {
  data: ErrorResponse
  status: 409
}

export type getResultApiV1AttemptsAttemptIdResultGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getResultApiV1AttemptsAttemptIdResultGetResponse500 = {
  data: ErrorResponse
  status: 500
}

export type getResultApiV1AttemptsAttemptIdResultGetResponseSuccess = (getResultApiV1AttemptsAttemptIdResultGetResponse200) & {
  headers: Headers;
};
export type getResultApiV1AttemptsAttemptIdResultGetResponseError = (getResultApiV1AttemptsAttemptIdResultGetResponse400 | getResultApiV1AttemptsAttemptIdResultGetResponse401 | getResultApiV1AttemptsAttemptIdResultGetResponse403 | getResultApiV1AttemptsAttemptIdResultGetResponse404 | getResultApiV1AttemptsAttemptIdResultGetResponse409 | getResultApiV1AttemptsAttemptIdResultGetResponse422 | getResultApiV1AttemptsAttemptIdResultGetResponse500) & {
  headers: Headers;
};

export type getResultApiV1AttemptsAttemptIdResultGetResponse = (getResultApiV1AttemptsAttemptIdResultGetResponseSuccess | getResultApiV1AttemptsAttemptIdResultGetResponseError)

export const getGetResultApiV1AttemptsAttemptIdResultGetUrl = (attemptId: number,) => {




  return `/api/v1/attempts/${attemptId}/result`
}

/**
 * @summary Get Result
 */
export const getResultApiV1AttemptsAttemptIdResultGet = async (attemptId: number, options?: RequestInit): Promise<getResultApiV1AttemptsAttemptIdResultGetResponse> => {

  return request<getResultApiV1AttemptsAttemptIdResultGetResponse>(getGetResultApiV1AttemptsAttemptIdResultGetUrl(attemptId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetResultApiV1AttemptsAttemptIdResultGetQueryKey = (attemptId: number,) => {
    return [
    `/api/v1/attempts/${attemptId}/result`
    ] as const;
    }


export const getGetResultApiV1AttemptsAttemptIdResultGetQueryOptions = <TData = Awaited<ReturnType<typeof getResultApiV1AttemptsAttemptIdResultGet>>, TError = ErrorResponse | HTTPValidationError>(attemptId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getResultApiV1AttemptsAttemptIdResultGet>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetResultApiV1AttemptsAttemptIdResultGetQueryKey(attemptId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getResultApiV1AttemptsAttemptIdResultGet>>> = ({ signal }) => getResultApiV1AttemptsAttemptIdResultGet(attemptId, { signal });





   return  { queryKey, queryFn, enabled: attemptId !== null && attemptId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getResultApiV1AttemptsAttemptIdResultGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetResultApiV1AttemptsAttemptIdResultGetQueryResult = NonNullable<Awaited<ReturnType<typeof getResultApiV1AttemptsAttemptIdResultGet>>>
export type GetResultApiV1AttemptsAttemptIdResultGetQueryError = ErrorResponse | HTTPValidationError


/**
 * @summary Get Result
 */

export function useGetResultApiV1AttemptsAttemptIdResultGet<TData = Awaited<ReturnType<typeof getResultApiV1AttemptsAttemptIdResultGet>>, TError = ErrorResponse | HTTPValidationError>(
 attemptId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getResultApiV1AttemptsAttemptIdResultGet>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetResultApiV1AttemptsAttemptIdResultGetQueryOptions(attemptId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






