/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Test Constructor API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  HTTPValidationError,
  LoginRequest,
  TokenResponse,
  UserCreate,
  UserResponse
} from './testConstructorAPI.schemas';

import { request } from '../axios';





export type registerApiV1AuthRegisterPostResponse201 = {
  data: UserResponse
  status: 201
}

export type registerApiV1AuthRegisterPostResponse400 = {
  data: ErrorResponse
  status: 400
}

export type registerApiV1AuthRegisterPostResponse401 = {
  data: ErrorResponse
  status: 401
}

export type registerApiV1AuthRegisterPostResponse403 = {
  data: ErrorResponse
  status: 403
}

export type registerApiV1AuthRegisterPostResponse404 = {
  data: ErrorResponse
  status: 404
}

export type registerApiV1AuthRegisterPostResponse409 = {
  data: ErrorResponse
  status: 409
}

export type registerApiV1AuthRegisterPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type registerApiV1AuthRegisterPostResponse500 = {
  data: ErrorResponse
  status: 500
}

export type registerApiV1AuthRegisterPostResponseSuccess = (registerApiV1AuthRegisterPostResponse201) & {
  headers: Headers;
};
export type registerApiV1AuthRegisterPostResponseError = (registerApiV1AuthRegisterPostResponse400 | registerApiV1AuthRegisterPostResponse401 | registerApiV1AuthRegisterPostResponse403 | registerApiV1AuthRegisterPostResponse404 | registerApiV1AuthRegisterPostResponse409 | registerApiV1AuthRegisterPostResponse422 | registerApiV1AuthRegisterPostResponse500) & {
  headers: Headers;
};

export type registerApiV1AuthRegisterPostResponse = (registerApiV1AuthRegisterPostResponseSuccess | registerApiV1AuthRegisterPostResponseError)

export const getRegisterApiV1AuthRegisterPostUrl = () => {




  return `/api/v1/auth/register`
}

/**
 * @summary Register
 */
export const registerApiV1AuthRegisterPost = async (userCreate: UserCreate, options?: RequestInit): Promise<registerApiV1AuthRegisterPostResponse> => {

  return request<registerApiV1AuthRegisterPostResponse>(getRegisterApiV1AuthRegisterPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(userCreate)
  }
);}





export const getRegisterApiV1AuthRegisterPostQueryKey = (userCreate?: UserCreate,) => {
    return [
    'POST', `/api/v1/auth/register`, userCreate
    ] as const;
    }


export const getRegisterApiV1AuthRegisterPostQueryOptions = <TData = Awaited<ReturnType<typeof registerApiV1AuthRegisterPost>>, TError = ErrorResponse | HTTPValidationError>(userCreate: UserCreate, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof registerApiV1AuthRegisterPost>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRegisterApiV1AuthRegisterPostQueryKey(userCreate);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof registerApiV1AuthRegisterPost>>> = ({ signal }) => registerApiV1AuthRegisterPost(userCreate, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof registerApiV1AuthRegisterPost>>, TError, TData> & { queryKey: QueryKey }
}

export type RegisterApiV1AuthRegisterPostQueryResult = NonNullable<Awaited<ReturnType<typeof registerApiV1AuthRegisterPost>>>
export type RegisterApiV1AuthRegisterPostQueryError = ErrorResponse | HTTPValidationError


/**
 * @summary Register
 */

export function useRegisterApiV1AuthRegisterPost<TData = Awaited<ReturnType<typeof registerApiV1AuthRegisterPost>>, TError = ErrorResponse | HTTPValidationError>(
 userCreate: UserCreate, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof registerApiV1AuthRegisterPost>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getRegisterApiV1AuthRegisterPostQueryOptions(userCreate,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type loginApiV1AuthLoginPostResponse200 = {
  data: TokenResponse
  status: 200
}

export type loginApiV1AuthLoginPostResponse400 = {
  data: ErrorResponse
  status: 400
}

export type loginApiV1AuthLoginPostResponse401 = {
  data: ErrorResponse
  status: 401
}

export type loginApiV1AuthLoginPostResponse403 = {
  data: ErrorResponse
  status: 403
}

export type loginApiV1AuthLoginPostResponse404 = {
  data: ErrorResponse
  status: 404
}

export type loginApiV1AuthLoginPostResponse409 = {
  data: ErrorResponse
  status: 409
}

export type loginApiV1AuthLoginPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type loginApiV1AuthLoginPostResponse500 = {
  data: ErrorResponse
  status: 500
}

export type loginApiV1AuthLoginPostResponseSuccess = (loginApiV1AuthLoginPostResponse200) & {
  headers: Headers;
};
export type loginApiV1AuthLoginPostResponseError = (loginApiV1AuthLoginPostResponse400 | loginApiV1AuthLoginPostResponse401 | loginApiV1AuthLoginPostResponse403 | loginApiV1AuthLoginPostResponse404 | loginApiV1AuthLoginPostResponse409 | loginApiV1AuthLoginPostResponse422 | loginApiV1AuthLoginPostResponse500) & {
  headers: Headers;
};

export type loginApiV1AuthLoginPostResponse = (loginApiV1AuthLoginPostResponseSuccess | loginApiV1AuthLoginPostResponseError)

export const getLoginApiV1AuthLoginPostUrl = () => {




  return `/api/v1/auth/login`
}

/**
 * @summary Login
 */
export const loginApiV1AuthLoginPost = async (loginRequest: LoginRequest, options?: RequestInit): Promise<loginApiV1AuthLoginPostResponse> => {

  return request<loginApiV1AuthLoginPostResponse>(getLoginApiV1AuthLoginPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(loginRequest)
  }
);}





export const getLoginApiV1AuthLoginPostQueryKey = (loginRequest?: LoginRequest,) => {
    return [
    'POST', `/api/v1/auth/login`, loginRequest
    ] as const;
    }


export const getLoginApiV1AuthLoginPostQueryOptions = <TData = Awaited<ReturnType<typeof loginApiV1AuthLoginPost>>, TError = ErrorResponse | HTTPValidationError>(loginRequest: LoginRequest, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof loginApiV1AuthLoginPost>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLoginApiV1AuthLoginPostQueryKey(loginRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof loginApiV1AuthLoginPost>>> = ({ signal }) => loginApiV1AuthLoginPost(loginRequest, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof loginApiV1AuthLoginPost>>, TError, TData> & { queryKey: QueryKey }
}

export type LoginApiV1AuthLoginPostQueryResult = NonNullable<Awaited<ReturnType<typeof loginApiV1AuthLoginPost>>>
export type LoginApiV1AuthLoginPostQueryError = ErrorResponse | HTTPValidationError


/**
 * @summary Login
 */

export function useLoginApiV1AuthLoginPost<TData = Awaited<ReturnType<typeof loginApiV1AuthLoginPost>>, TError = ErrorResponse | HTTPValidationError>(
 loginRequest: LoginRequest, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof loginApiV1AuthLoginPost>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getLoginApiV1AuthLoginPostQueryOptions(loginRequest,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type getCurrentUserProfileApiV1AuthMeGetResponse200 = {
  data: UserResponse
  status: 200
}

export type getCurrentUserProfileApiV1AuthMeGetResponse400 = {
  data: ErrorResponse
  status: 400
}

export type getCurrentUserProfileApiV1AuthMeGetResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getCurrentUserProfileApiV1AuthMeGetResponse403 = {
  data: ErrorResponse
  status: 403
}

export type getCurrentUserProfileApiV1AuthMeGetResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getCurrentUserProfileApiV1AuthMeGetResponse409 = {
  data: ErrorResponse
  status: 409
}

export type getCurrentUserProfileApiV1AuthMeGetResponse422 = {
  data: ErrorResponse
  status: 422
}

export type getCurrentUserProfileApiV1AuthMeGetResponse500 = {
  data: ErrorResponse
  status: 500
}

export type getCurrentUserProfileApiV1AuthMeGetResponseSuccess = (getCurrentUserProfileApiV1AuthMeGetResponse200) & {
  headers: Headers;
};
export type getCurrentUserProfileApiV1AuthMeGetResponseError = (getCurrentUserProfileApiV1AuthMeGetResponse400 | getCurrentUserProfileApiV1AuthMeGetResponse401 | getCurrentUserProfileApiV1AuthMeGetResponse403 | getCurrentUserProfileApiV1AuthMeGetResponse404 | getCurrentUserProfileApiV1AuthMeGetResponse409 | getCurrentUserProfileApiV1AuthMeGetResponse422 | getCurrentUserProfileApiV1AuthMeGetResponse500) & {
  headers: Headers;
};

export type getCurrentUserProfileApiV1AuthMeGetResponse = (getCurrentUserProfileApiV1AuthMeGetResponseSuccess | getCurrentUserProfileApiV1AuthMeGetResponseError)

export const getGetCurrentUserProfileApiV1AuthMeGetUrl = () => {




  return `/api/v1/auth/me`
}

/**
 * @summary Get Current User Profile
 */
export const getCurrentUserProfileApiV1AuthMeGet = async ( options?: RequestInit): Promise<getCurrentUserProfileApiV1AuthMeGetResponse> => {

  return request<getCurrentUserProfileApiV1AuthMeGetResponse>(getGetCurrentUserProfileApiV1AuthMeGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCurrentUserProfileApiV1AuthMeGetQueryKey = () => {
    return [
    `/api/v1/auth/me`
    ] as const;
    }


export const getGetCurrentUserProfileApiV1AuthMeGetQueryOptions = <TData = Awaited<ReturnType<typeof getCurrentUserProfileApiV1AuthMeGet>>, TError = ErrorResponse>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCurrentUserProfileApiV1AuthMeGet>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCurrentUserProfileApiV1AuthMeGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrentUserProfileApiV1AuthMeGet>>> = ({ signal }) => getCurrentUserProfileApiV1AuthMeGet({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCurrentUserProfileApiV1AuthMeGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetCurrentUserProfileApiV1AuthMeGetQueryResult = NonNullable<Awaited<ReturnType<typeof getCurrentUserProfileApiV1AuthMeGet>>>
export type GetCurrentUserProfileApiV1AuthMeGetQueryError = ErrorResponse


/**
 * @summary Get Current User Profile
 */

export function useGetCurrentUserProfileApiV1AuthMeGet<TData = Awaited<ReturnType<typeof getCurrentUserProfileApiV1AuthMeGet>>, TError = ErrorResponse>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCurrentUserProfileApiV1AuthMeGet>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetCurrentUserProfileApiV1AuthMeGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






