/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Test Constructor API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  HTTPValidationError,
  SearchCatalogApiV1CatalogGetParams,
  TestDetailResponse,
  TestResponse
} from './testConstructorAPI.schemas';

import { request } from '../axios';





export type searchCatalogApiV1CatalogGetResponse200 = {
  data: TestResponse[]
  status: 200
}

export type searchCatalogApiV1CatalogGetResponse400 = {
  data: ErrorResponse
  status: 400
}

export type searchCatalogApiV1CatalogGetResponse401 = {
  data: ErrorResponse
  status: 401
}

export type searchCatalogApiV1CatalogGetResponse403 = {
  data: ErrorResponse
  status: 403
}

export type searchCatalogApiV1CatalogGetResponse404 = {
  data: ErrorResponse
  status: 404
}

export type searchCatalogApiV1CatalogGetResponse409 = {
  data: ErrorResponse
  status: 409
}

export type searchCatalogApiV1CatalogGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type searchCatalogApiV1CatalogGetResponse500 = {
  data: ErrorResponse
  status: 500
}

export type searchCatalogApiV1CatalogGetResponseSuccess = (searchCatalogApiV1CatalogGetResponse200) & {
  headers: Headers;
};
export type searchCatalogApiV1CatalogGetResponseError = (searchCatalogApiV1CatalogGetResponse400 | searchCatalogApiV1CatalogGetResponse401 | searchCatalogApiV1CatalogGetResponse403 | searchCatalogApiV1CatalogGetResponse404 | searchCatalogApiV1CatalogGetResponse409 | searchCatalogApiV1CatalogGetResponse422 | searchCatalogApiV1CatalogGetResponse500) & {
  headers: Headers;
};

export type searchCatalogApiV1CatalogGetResponse = (searchCatalogApiV1CatalogGetResponseSuccess | searchCatalogApiV1CatalogGetResponseError)

export const getSearchCatalogApiV1CatalogGetUrl = (params?: SearchCatalogApiV1CatalogGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/catalog/?${stringifiedParams}` : `/api/v1/catalog/`
}

/**
 * @summary Search Catalog
 */
export const searchCatalogApiV1CatalogGet = async (params?: SearchCatalogApiV1CatalogGetParams, options?: RequestInit): Promise<searchCatalogApiV1CatalogGetResponse> => {

  return request<searchCatalogApiV1CatalogGetResponse>(getSearchCatalogApiV1CatalogGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getSearchCatalogApiV1CatalogGetQueryKey = (params?: SearchCatalogApiV1CatalogGetParams,) => {
    return [
    `/api/v1/catalog/`, ...(params ? [params] : [])
    ] as const;
    }


export const getSearchCatalogApiV1CatalogGetQueryOptions = <TData = Awaited<ReturnType<typeof searchCatalogApiV1CatalogGet>>, TError = ErrorResponse | HTTPValidationError>(params?: SearchCatalogApiV1CatalogGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof searchCatalogApiV1CatalogGet>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchCatalogApiV1CatalogGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchCatalogApiV1CatalogGet>>> = ({ signal }) => searchCatalogApiV1CatalogGet(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchCatalogApiV1CatalogGet>>, TError, TData> & { queryKey: QueryKey }
}

export type SearchCatalogApiV1CatalogGetQueryResult = NonNullable<Awaited<ReturnType<typeof searchCatalogApiV1CatalogGet>>>
export type SearchCatalogApiV1CatalogGetQueryError = ErrorResponse | HTTPValidationError


/**
 * @summary Search Catalog
 */

export function useSearchCatalogApiV1CatalogGet<TData = Awaited<ReturnType<typeof searchCatalogApiV1CatalogGet>>, TError = ErrorResponse | HTTPValidationError>(
 params?: SearchCatalogApiV1CatalogGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof searchCatalogApiV1CatalogGet>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getSearchCatalogApiV1CatalogGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type getPublicTestApiV1CatalogTestIdGetResponse200 = {
  data: TestDetailResponse
  status: 200
}

export type getPublicTestApiV1CatalogTestIdGetResponse400 = {
  data: ErrorResponse
  status: 400
}

export type getPublicTestApiV1CatalogTestIdGetResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getPublicTestApiV1CatalogTestIdGetResponse403 = {
  data: ErrorResponse
  status: 403
}

export type getPublicTestApiV1CatalogTestIdGetResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getPublicTestApiV1CatalogTestIdGetResponse409 = {
  data: ErrorResponse
  status: 409
}

export type getPublicTestApiV1CatalogTestIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getPublicTestApiV1CatalogTestIdGetResponse500 = {
  data: ErrorResponse
  status: 500
}

export type getPublicTestApiV1CatalogTestIdGetResponseSuccess = (getPublicTestApiV1CatalogTestIdGetResponse200) & {
  headers: Headers;
};
export type getPublicTestApiV1CatalogTestIdGetResponseError = (getPublicTestApiV1CatalogTestIdGetResponse400 | getPublicTestApiV1CatalogTestIdGetResponse401 | getPublicTestApiV1CatalogTestIdGetResponse403 | getPublicTestApiV1CatalogTestIdGetResponse404 | getPublicTestApiV1CatalogTestIdGetResponse409 | getPublicTestApiV1CatalogTestIdGetResponse422 | getPublicTestApiV1CatalogTestIdGetResponse500) & {
  headers: Headers;
};

export type getPublicTestApiV1CatalogTestIdGetResponse = (getPublicTestApiV1CatalogTestIdGetResponseSuccess | getPublicTestApiV1CatalogTestIdGetResponseError)

export const getGetPublicTestApiV1CatalogTestIdGetUrl = (testId: number,) => {




  return `/api/v1/catalog/${testId}`
}

/**
 * @summary Get Public Test
 */
export const getPublicTestApiV1CatalogTestIdGet = async (testId: number, options?: RequestInit): Promise<getPublicTestApiV1CatalogTestIdGetResponse> => {

  return request<getPublicTestApiV1CatalogTestIdGetResponse>(getGetPublicTestApiV1CatalogTestIdGetUrl(testId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPublicTestApiV1CatalogTestIdGetQueryKey = (testId: number,) => {
    return [
    `/api/v1/catalog/${testId}`
    ] as const;
    }


export const getGetPublicTestApiV1CatalogTestIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getPublicTestApiV1CatalogTestIdGet>>, TError = ErrorResponse | HTTPValidationError>(testId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPublicTestApiV1CatalogTestIdGet>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPublicTestApiV1CatalogTestIdGetQueryKey(testId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPublicTestApiV1CatalogTestIdGet>>> = ({ signal }) => getPublicTestApiV1CatalogTestIdGet(testId, { signal });





   return  { queryKey, queryFn, enabled: testId !== null && testId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPublicTestApiV1CatalogTestIdGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetPublicTestApiV1CatalogTestIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getPublicTestApiV1CatalogTestIdGet>>>
export type GetPublicTestApiV1CatalogTestIdGetQueryError = ErrorResponse | HTTPValidationError


/**
 * @summary Get Public Test
 */

export function useGetPublicTestApiV1CatalogTestIdGet<TData = Awaited<ReturnType<typeof getPublicTestApiV1CatalogTestIdGet>>, TError = ErrorResponse | HTTPValidationError>(
 testId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPublicTestApiV1CatalogTestIdGet>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetPublicTestApiV1CatalogTestIdGetQueryOptions(testId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






