/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Test Constructor API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  RootGet200
} from './testConstructorAPI.schemas';

import { request } from '../axios';





export type rootGetResponse200 = {
  data: RootGet200
  status: 200
}

export type rootGetResponse400 = {
  data: ErrorResponse
  status: 400
}

export type rootGetResponse401 = {
  data: ErrorResponse
  status: 401
}

export type rootGetResponse403 = {
  data: ErrorResponse
  status: 403
}

export type rootGetResponse404 = {
  data: ErrorResponse
  status: 404
}

export type rootGetResponse409 = {
  data: ErrorResponse
  status: 409
}

export type rootGetResponse422 = {
  data: ErrorResponse
  status: 422
}

export type rootGetResponse500 = {
  data: ErrorResponse
  status: 500
}

export type rootGetResponseSuccess = (rootGetResponse200) & {
  headers: Headers;
};
export type rootGetResponseError = (rootGetResponse400 | rootGetResponse401 | rootGetResponse403 | rootGetResponse404 | rootGetResponse409 | rootGetResponse422 | rootGetResponse500) & {
  headers: Headers;
};

export type rootGetResponse = (rootGetResponseSuccess | rootGetResponseError)

export const getRootGetUrl = () => {




  return `/`
}

/**
 * @summary Root
 */
export const rootGet = async ( options?: RequestInit): Promise<rootGetResponse> => {

  return request<rootGetResponse>(getRootGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getRootGetQueryKey = () => {
    return [
    `/`
    ] as const;
    }


export const getRootGetQueryOptions = <TData = Awaited<ReturnType<typeof rootGet>>, TError = ErrorResponse>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRootGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof rootGet>>> = ({ signal }) => rootGet({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData> & { queryKey: QueryKey }
}

export type RootGetQueryResult = NonNullable<Awaited<ReturnType<typeof rootGet>>>
export type RootGetQueryError = ErrorResponse


/**
 * @summary Root
 */

export function useRootGet<TData = Awaited<ReturnType<typeof rootGet>>, TError = ErrorResponse>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getRootGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






