/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Test Constructor API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  HealthCheckApiV1HealthGet200,
  PingApiV1PingGet200
} from './testConstructorAPI.schemas';

import { request } from '../axios';





export type healthCheckApiV1HealthGetResponse200 = {
  data: HealthCheckApiV1HealthGet200
  status: 200
}

export type healthCheckApiV1HealthGetResponse400 = {
  data: ErrorResponse
  status: 400
}

export type healthCheckApiV1HealthGetResponse401 = {
  data: ErrorResponse
  status: 401
}

export type healthCheckApiV1HealthGetResponse403 = {
  data: ErrorResponse
  status: 403
}

export type healthCheckApiV1HealthGetResponse404 = {
  data: ErrorResponse
  status: 404
}

export type healthCheckApiV1HealthGetResponse409 = {
  data: ErrorResponse
  status: 409
}

export type healthCheckApiV1HealthGetResponse422 = {
  data: ErrorResponse
  status: 422
}

export type healthCheckApiV1HealthGetResponse500 = {
  data: ErrorResponse
  status: 500
}

export type healthCheckApiV1HealthGetResponseSuccess = (healthCheckApiV1HealthGetResponse200) & {
  headers: Headers;
};
export type healthCheckApiV1HealthGetResponseError = (healthCheckApiV1HealthGetResponse400 | healthCheckApiV1HealthGetResponse401 | healthCheckApiV1HealthGetResponse403 | healthCheckApiV1HealthGetResponse404 | healthCheckApiV1HealthGetResponse409 | healthCheckApiV1HealthGetResponse422 | healthCheckApiV1HealthGetResponse500) & {
  headers: Headers;
};

export type healthCheckApiV1HealthGetResponse = (healthCheckApiV1HealthGetResponseSuccess | healthCheckApiV1HealthGetResponseError)

export const getHealthCheckApiV1HealthGetUrl = () => {




  return `/api/v1/health`
}

/**
 * Health check endpoint

Returns:
    dict: Application health status
 * @summary Health Check
 */
export const healthCheckApiV1HealthGet = async ( options?: RequestInit): Promise<healthCheckApiV1HealthGetResponse> => {

  return request<healthCheckApiV1HealthGetResponse>(getHealthCheckApiV1HealthGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getHealthCheckApiV1HealthGetQueryKey = () => {
    return [
    `/api/v1/health`
    ] as const;
    }


export const getHealthCheckApiV1HealthGetQueryOptions = <TData = Awaited<ReturnType<typeof healthCheckApiV1HealthGet>>, TError = ErrorResponse>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheckApiV1HealthGet>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthCheckApiV1HealthGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheckApiV1HealthGet>>> = ({ signal }) => healthCheckApiV1HealthGet({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthCheckApiV1HealthGet>>, TError, TData> & { queryKey: QueryKey }
}

export type HealthCheckApiV1HealthGetQueryResult = NonNullable<Awaited<ReturnType<typeof healthCheckApiV1HealthGet>>>
export type HealthCheckApiV1HealthGetQueryError = ErrorResponse


/**
 * @summary Health Check
 */

export function useHealthCheckApiV1HealthGet<TData = Awaited<ReturnType<typeof healthCheckApiV1HealthGet>>, TError = ErrorResponse>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheckApiV1HealthGet>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getHealthCheckApiV1HealthGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type pingApiV1PingGetResponse200 = {
  data: PingApiV1PingGet200
  status: 200
}

export type pingApiV1PingGetResponse400 = {
  data: ErrorResponse
  status: 400
}

export type pingApiV1PingGetResponse401 = {
  data: ErrorResponse
  status: 401
}

export type pingApiV1PingGetResponse403 = {
  data: ErrorResponse
  status: 403
}

export type pingApiV1PingGetResponse404 = {
  data: ErrorResponse
  status: 404
}

export type pingApiV1PingGetResponse409 = {
  data: ErrorResponse
  status: 409
}

export type pingApiV1PingGetResponse422 = {
  data: ErrorResponse
  status: 422
}

export type pingApiV1PingGetResponse500 = {
  data: ErrorResponse
  status: 500
}

export type pingApiV1PingGetResponseSuccess = (pingApiV1PingGetResponse200) & {
  headers: Headers;
};
export type pingApiV1PingGetResponseError = (pingApiV1PingGetResponse400 | pingApiV1PingGetResponse401 | pingApiV1PingGetResponse403 | pingApiV1PingGetResponse404 | pingApiV1PingGetResponse409 | pingApiV1PingGetResponse422 | pingApiV1PingGetResponse500) & {
  headers: Headers;
};

export type pingApiV1PingGetResponse = (pingApiV1PingGetResponseSuccess | pingApiV1PingGetResponseError)

export const getPingApiV1PingGetUrl = () => {




  return `/api/v1/ping`
}

/**
 * Simple ping endpoint

Returns:
    dict: Pong response
 * @summary Ping
 */
export const pingApiV1PingGet = async ( options?: RequestInit): Promise<pingApiV1PingGetResponse> => {

  return request<pingApiV1PingGetResponse>(getPingApiV1PingGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getPingApiV1PingGetQueryKey = () => {
    return [
    `/api/v1/ping`
    ] as const;
    }


export const getPingApiV1PingGetQueryOptions = <TData = Awaited<ReturnType<typeof pingApiV1PingGet>>, TError = ErrorResponse>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof pingApiV1PingGet>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPingApiV1PingGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof pingApiV1PingGet>>> = ({ signal }) => pingApiV1PingGet({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof pingApiV1PingGet>>, TError, TData> & { queryKey: QueryKey }
}

export type PingApiV1PingGetQueryResult = NonNullable<Awaited<ReturnType<typeof pingApiV1PingGet>>>
export type PingApiV1PingGetQueryError = ErrorResponse


/**
 * @summary Ping
 */

export function usePingApiV1PingGet<TData = Awaited<ReturnType<typeof pingApiV1PingGet>>, TError = ErrorResponse>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof pingApiV1PingGet>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getPingApiV1PingGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






