/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Test Constructor API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BodyUploadMediaApiV1MediaUploadPost,
  ErrorResponse,
  HTTPValidationError,
  UploadMediaApiV1MediaUploadPost201
} from './testConstructorAPI.schemas';

import { request } from '../axios';





export type uploadMediaApiV1MediaUploadPostResponse201 = {
  data: UploadMediaApiV1MediaUploadPost201
  status: 201
}

export type uploadMediaApiV1MediaUploadPostResponse400 = {
  data: ErrorResponse
  status: 400
}

export type uploadMediaApiV1MediaUploadPostResponse401 = {
  data: ErrorResponse
  status: 401
}

export type uploadMediaApiV1MediaUploadPostResponse403 = {
  data: ErrorResponse
  status: 403
}

export type uploadMediaApiV1MediaUploadPostResponse404 = {
  data: ErrorResponse
  status: 404
}

export type uploadMediaApiV1MediaUploadPostResponse409 = {
  data: ErrorResponse
  status: 409
}

export type uploadMediaApiV1MediaUploadPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type uploadMediaApiV1MediaUploadPostResponse500 = {
  data: ErrorResponse
  status: 500
}

export type uploadMediaApiV1MediaUploadPostResponseSuccess = (uploadMediaApiV1MediaUploadPostResponse201) & {
  headers: Headers;
};
export type uploadMediaApiV1MediaUploadPostResponseError = (uploadMediaApiV1MediaUploadPostResponse400 | uploadMediaApiV1MediaUploadPostResponse401 | uploadMediaApiV1MediaUploadPostResponse403 | uploadMediaApiV1MediaUploadPostResponse404 | uploadMediaApiV1MediaUploadPostResponse409 | uploadMediaApiV1MediaUploadPostResponse422 | uploadMediaApiV1MediaUploadPostResponse500) & {
  headers: Headers;
};

export type uploadMediaApiV1MediaUploadPostResponse = (uploadMediaApiV1MediaUploadPostResponseSuccess | uploadMediaApiV1MediaUploadPostResponseError)

export const getUploadMediaApiV1MediaUploadPostUrl = () => {




  return `/api/v1/media/upload`
}

/**
 * @summary Upload Media
 */
export const uploadMediaApiV1MediaUploadPost = async (bodyUploadMediaApiV1MediaUploadPost: BodyUploadMediaApiV1MediaUploadPost, options?: RequestInit): Promise<uploadMediaApiV1MediaUploadPostResponse> => {
    const formData = new FormData();
formData.append(`file`, bodyUploadMediaApiV1MediaUploadPost.file);

  return request<uploadMediaApiV1MediaUploadPostResponse>(getUploadMediaApiV1MediaUploadPostUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body: formData
  }
);}





export const getUploadMediaApiV1MediaUploadPostQueryKey = (bodyUploadMediaApiV1MediaUploadPost?: BodyUploadMediaApiV1MediaUploadPost,) => {
    return [
    'POST', `/api/v1/media/upload`, bodyUploadMediaApiV1MediaUploadPost
    ] as const;
    }


export const getUploadMediaApiV1MediaUploadPostQueryOptions = <TData = Awaited<ReturnType<typeof uploadMediaApiV1MediaUploadPost>>, TError = ErrorResponse | HTTPValidationError>(bodyUploadMediaApiV1MediaUploadPost: BodyUploadMediaApiV1MediaUploadPost, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof uploadMediaApiV1MediaUploadPost>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUploadMediaApiV1MediaUploadPostQueryKey(bodyUploadMediaApiV1MediaUploadPost);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof uploadMediaApiV1MediaUploadPost>>> = ({ signal }) => uploadMediaApiV1MediaUploadPost(bodyUploadMediaApiV1MediaUploadPost, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof uploadMediaApiV1MediaUploadPost>>, TError, TData> & { queryKey: QueryKey }
}

export type UploadMediaApiV1MediaUploadPostQueryResult = NonNullable<Awaited<ReturnType<typeof uploadMediaApiV1MediaUploadPost>>>
export type UploadMediaApiV1MediaUploadPostQueryError = ErrorResponse | HTTPValidationError


/**
 * @summary Upload Media
 */

export function useUploadMediaApiV1MediaUploadPost<TData = Awaited<ReturnType<typeof uploadMediaApiV1MediaUploadPost>>, TError = ErrorResponse | HTTPValidationError>(
 bodyUploadMediaApiV1MediaUploadPost: BodyUploadMediaApiV1MediaUploadPost, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof uploadMediaApiV1MediaUploadPost>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getUploadMediaApiV1MediaUploadPostQueryOptions(bodyUploadMediaApiV1MediaUploadPost,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






