/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Test Constructor API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthorStatsResponse,
  ErrorResponse,
  HTTPValidationError,
  TestStatsResponse
} from './testConstructorAPI.schemas';

import { request } from '../axios';





export type getAuthorStatsApiV1StatsMeGetResponse200 = {
  data: AuthorStatsResponse
  status: 200
}

export type getAuthorStatsApiV1StatsMeGetResponse400 = {
  data: ErrorResponse
  status: 400
}

export type getAuthorStatsApiV1StatsMeGetResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getAuthorStatsApiV1StatsMeGetResponse403 = {
  data: ErrorResponse
  status: 403
}

export type getAuthorStatsApiV1StatsMeGetResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getAuthorStatsApiV1StatsMeGetResponse409 = {
  data: ErrorResponse
  status: 409
}

export type getAuthorStatsApiV1StatsMeGetResponse422 = {
  data: ErrorResponse
  status: 422
}

export type getAuthorStatsApiV1StatsMeGetResponse500 = {
  data: ErrorResponse
  status: 500
}

export type getAuthorStatsApiV1StatsMeGetResponseSuccess = (getAuthorStatsApiV1StatsMeGetResponse200) & {
  headers: Headers;
};
export type getAuthorStatsApiV1StatsMeGetResponseError = (getAuthorStatsApiV1StatsMeGetResponse400 | getAuthorStatsApiV1StatsMeGetResponse401 | getAuthorStatsApiV1StatsMeGetResponse403 | getAuthorStatsApiV1StatsMeGetResponse404 | getAuthorStatsApiV1StatsMeGetResponse409 | getAuthorStatsApiV1StatsMeGetResponse422 | getAuthorStatsApiV1StatsMeGetResponse500) & {
  headers: Headers;
};

export type getAuthorStatsApiV1StatsMeGetResponse = (getAuthorStatsApiV1StatsMeGetResponseSuccess | getAuthorStatsApiV1StatsMeGetResponseError)

export const getGetAuthorStatsApiV1StatsMeGetUrl = () => {




  return `/api/v1/stats/me`
}

/**
 * @summary Get Author Stats
 */
export const getAuthorStatsApiV1StatsMeGet = async ( options?: RequestInit): Promise<getAuthorStatsApiV1StatsMeGetResponse> => {

  return request<getAuthorStatsApiV1StatsMeGetResponse>(getGetAuthorStatsApiV1StatsMeGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAuthorStatsApiV1StatsMeGetQueryKey = () => {
    return [
    `/api/v1/stats/me`
    ] as const;
    }


export const getGetAuthorStatsApiV1StatsMeGetQueryOptions = <TData = Awaited<ReturnType<typeof getAuthorStatsApiV1StatsMeGet>>, TError = ErrorResponse>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAuthorStatsApiV1StatsMeGet>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAuthorStatsApiV1StatsMeGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthorStatsApiV1StatsMeGet>>> = ({ signal }) => getAuthorStatsApiV1StatsMeGet({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAuthorStatsApiV1StatsMeGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAuthorStatsApiV1StatsMeGetQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthorStatsApiV1StatsMeGet>>>
export type GetAuthorStatsApiV1StatsMeGetQueryError = ErrorResponse


/**
 * @summary Get Author Stats
 */

export function useGetAuthorStatsApiV1StatsMeGet<TData = Awaited<ReturnType<typeof getAuthorStatsApiV1StatsMeGet>>, TError = ErrorResponse>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAuthorStatsApiV1StatsMeGet>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAuthorStatsApiV1StatsMeGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type getTestStatsApiV1StatsTestsTestIdGetResponse200 = {
  data: TestStatsResponse
  status: 200
}

export type getTestStatsApiV1StatsTestsTestIdGetResponse400 = {
  data: ErrorResponse
  status: 400
}

export type getTestStatsApiV1StatsTestsTestIdGetResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getTestStatsApiV1StatsTestsTestIdGetResponse403 = {
  data: ErrorResponse
  status: 403
}

export type getTestStatsApiV1StatsTestsTestIdGetResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getTestStatsApiV1StatsTestsTestIdGetResponse409 = {
  data: ErrorResponse
  status: 409
}

export type getTestStatsApiV1StatsTestsTestIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getTestStatsApiV1StatsTestsTestIdGetResponse500 = {
  data: ErrorResponse
  status: 500
}

export type getTestStatsApiV1StatsTestsTestIdGetResponseSuccess = (getTestStatsApiV1StatsTestsTestIdGetResponse200) & {
  headers: Headers;
};
export type getTestStatsApiV1StatsTestsTestIdGetResponseError = (getTestStatsApiV1StatsTestsTestIdGetResponse400 | getTestStatsApiV1StatsTestsTestIdGetResponse401 | getTestStatsApiV1StatsTestsTestIdGetResponse403 | getTestStatsApiV1StatsTestsTestIdGetResponse404 | getTestStatsApiV1StatsTestsTestIdGetResponse409 | getTestStatsApiV1StatsTestsTestIdGetResponse422 | getTestStatsApiV1StatsTestsTestIdGetResponse500) & {
  headers: Headers;
};

export type getTestStatsApiV1StatsTestsTestIdGetResponse = (getTestStatsApiV1StatsTestsTestIdGetResponseSuccess | getTestStatsApiV1StatsTestsTestIdGetResponseError)

export const getGetTestStatsApiV1StatsTestsTestIdGetUrl = (testId: number,) => {




  return `/api/v1/stats/tests/${testId}`
}

/**
 * @summary Get Test Stats
 */
export const getTestStatsApiV1StatsTestsTestIdGet = async (testId: number, options?: RequestInit): Promise<getTestStatsApiV1StatsTestsTestIdGetResponse> => {

  return request<getTestStatsApiV1StatsTestsTestIdGetResponse>(getGetTestStatsApiV1StatsTestsTestIdGetUrl(testId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetTestStatsApiV1StatsTestsTestIdGetQueryKey = (testId: number,) => {
    return [
    `/api/v1/stats/tests/${testId}`
    ] as const;
    }


export const getGetTestStatsApiV1StatsTestsTestIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getTestStatsApiV1StatsTestsTestIdGet>>, TError = ErrorResponse | HTTPValidationError>(testId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTestStatsApiV1StatsTestsTestIdGet>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTestStatsApiV1StatsTestsTestIdGetQueryKey(testId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTestStatsApiV1StatsTestsTestIdGet>>> = ({ signal }) => getTestStatsApiV1StatsTestsTestIdGet(testId, { signal });





   return  { queryKey, queryFn, enabled: testId !== null && testId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTestStatsApiV1StatsTestsTestIdGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetTestStatsApiV1StatsTestsTestIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getTestStatsApiV1StatsTestsTestIdGet>>>
export type GetTestStatsApiV1StatsTestsTestIdGetQueryError = ErrorResponse | HTTPValidationError


/**
 * @summary Get Test Stats
 */

export function useGetTestStatsApiV1StatsTestsTestIdGet<TData = Awaited<ReturnType<typeof getTestStatsApiV1StatsTestsTestIdGet>>, TError = ErrorResponse | HTTPValidationError>(
 testId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTestStatsApiV1StatsTestsTestIdGet>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetTestStatsApiV1StatsTestsTestIdGetQueryOptions(testId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






