/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Test Constructor API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  HTTPValidationError,
  TagCreate,
  TagResponse
} from './testConstructorAPI.schemas';

import { request } from '../axios';





export type listTagsApiV1TagsGetResponse200 = {
  data: TagResponse[]
  status: 200
}

export type listTagsApiV1TagsGetResponse400 = {
  data: ErrorResponse
  status: 400
}

export type listTagsApiV1TagsGetResponse401 = {
  data: ErrorResponse
  status: 401
}

export type listTagsApiV1TagsGetResponse403 = {
  data: ErrorResponse
  status: 403
}

export type listTagsApiV1TagsGetResponse404 = {
  data: ErrorResponse
  status: 404
}

export type listTagsApiV1TagsGetResponse409 = {
  data: ErrorResponse
  status: 409
}

export type listTagsApiV1TagsGetResponse422 = {
  data: ErrorResponse
  status: 422
}

export type listTagsApiV1TagsGetResponse500 = {
  data: ErrorResponse
  status: 500
}

export type listTagsApiV1TagsGetResponseSuccess = (listTagsApiV1TagsGetResponse200) & {
  headers: Headers;
};
export type listTagsApiV1TagsGetResponseError = (listTagsApiV1TagsGetResponse400 | listTagsApiV1TagsGetResponse401 | listTagsApiV1TagsGetResponse403 | listTagsApiV1TagsGetResponse404 | listTagsApiV1TagsGetResponse409 | listTagsApiV1TagsGetResponse422 | listTagsApiV1TagsGetResponse500) & {
  headers: Headers;
};

export type listTagsApiV1TagsGetResponse = (listTagsApiV1TagsGetResponseSuccess | listTagsApiV1TagsGetResponseError)

export const getListTagsApiV1TagsGetUrl = () => {




  return `/api/v1/tags/`
}

/**
 * @summary List Tags
 */
export const listTagsApiV1TagsGet = async ( options?: RequestInit): Promise<listTagsApiV1TagsGetResponse> => {

  return request<listTagsApiV1TagsGetResponse>(getListTagsApiV1TagsGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListTagsApiV1TagsGetQueryKey = () => {
    return [
    `/api/v1/tags/`
    ] as const;
    }


export const getListTagsApiV1TagsGetQueryOptions = <TData = Awaited<ReturnType<typeof listTagsApiV1TagsGet>>, TError = ErrorResponse>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listTagsApiV1TagsGet>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListTagsApiV1TagsGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listTagsApiV1TagsGet>>> = ({ signal }) => listTagsApiV1TagsGet({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listTagsApiV1TagsGet>>, TError, TData> & { queryKey: QueryKey }
}

export type ListTagsApiV1TagsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listTagsApiV1TagsGet>>>
export type ListTagsApiV1TagsGetQueryError = ErrorResponse


/**
 * @summary List Tags
 */

export function useListTagsApiV1TagsGet<TData = Awaited<ReturnType<typeof listTagsApiV1TagsGet>>, TError = ErrorResponse>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listTagsApiV1TagsGet>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListTagsApiV1TagsGetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type createTagApiV1TagsPostResponse201 = {
  data: TagResponse
  status: 201
}

export type createTagApiV1TagsPostResponse400 = {
  data: ErrorResponse
  status: 400
}

export type createTagApiV1TagsPostResponse401 = {
  data: ErrorResponse
  status: 401
}

export type createTagApiV1TagsPostResponse403 = {
  data: ErrorResponse
  status: 403
}

export type createTagApiV1TagsPostResponse404 = {
  data: ErrorResponse
  status: 404
}

export type createTagApiV1TagsPostResponse409 = {
  data: ErrorResponse
  status: 409
}

export type createTagApiV1TagsPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createTagApiV1TagsPostResponse500 = {
  data: ErrorResponse
  status: 500
}

export type createTagApiV1TagsPostResponseSuccess = (createTagApiV1TagsPostResponse201) & {
  headers: Headers;
};
export type createTagApiV1TagsPostResponseError = (createTagApiV1TagsPostResponse400 | createTagApiV1TagsPostResponse401 | createTagApiV1TagsPostResponse403 | createTagApiV1TagsPostResponse404 | createTagApiV1TagsPostResponse409 | createTagApiV1TagsPostResponse422 | createTagApiV1TagsPostResponse500) & {
  headers: Headers;
};

export type createTagApiV1TagsPostResponse = (createTagApiV1TagsPostResponseSuccess | createTagApiV1TagsPostResponseError)

export const getCreateTagApiV1TagsPostUrl = () => {




  return `/api/v1/tags/`
}

/**
 * @summary Create Tag
 */
export const createTagApiV1TagsPost = async (tagCreate: TagCreate, options?: RequestInit): Promise<createTagApiV1TagsPostResponse> => {

  return request<createTagApiV1TagsPostResponse>(getCreateTagApiV1TagsPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(tagCreate)
  }
);}





export const getCreateTagApiV1TagsPostQueryKey = (tagCreate?: TagCreate,) => {
    return [
    'POST', `/api/v1/tags/`, tagCreate
    ] as const;
    }


export const getCreateTagApiV1TagsPostQueryOptions = <TData = Awaited<ReturnType<typeof createTagApiV1TagsPost>>, TError = ErrorResponse | HTTPValidationError>(tagCreate: TagCreate, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof createTagApiV1TagsPost>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCreateTagApiV1TagsPostQueryKey(tagCreate);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof createTagApiV1TagsPost>>> = ({ signal }) => createTagApiV1TagsPost(tagCreate, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof createTagApiV1TagsPost>>, TError, TData> & { queryKey: QueryKey }
}

export type CreateTagApiV1TagsPostQueryResult = NonNullable<Awaited<ReturnType<typeof createTagApiV1TagsPost>>>
export type CreateTagApiV1TagsPostQueryError = ErrorResponse | HTTPValidationError


/**
 * @summary Create Tag
 */

export function useCreateTagApiV1TagsPost<TData = Awaited<ReturnType<typeof createTagApiV1TagsPost>>, TError = ErrorResponse | HTTPValidationError>(
 tagCreate: TagCreate, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof createTagApiV1TagsPost>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getCreateTagApiV1TagsPostQueryOptions(tagCreate,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






