/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Test Constructor API
 * OpenAPI spec version: 1.0.0
 */
export interface AnswerResponse {
  id: number;
  question_id: number;
  selected_option_ids: number[] | null;
  text_answer: string | null;
  is_correct: boolean | null;
  points_earned: number | null;
}

export interface AnswerSubmitRequest {
  question_id: number;
  selected_option_ids?: number[] | null;
  text_answer?: string | null;
}

export type QuestionType = typeof QuestionType[keyof typeof QuestionType];


export const QuestionType = {
  single_choice: 'single_choice',
  multiple_choice: 'multiple_choice',
  text: 'text',
  essay: 'essay',
} as const;

export interface AttemptAnswerDetail {
  question_id: number;
  question_text: string;
  question_type: QuestionType;
  points: number;
  selected_option_ids: number[] | null;
  text_answer: string | null;
  is_correct: boolean | null;
  points_earned: number | null;
  correct_option_ids: number[];
  explanation: string | null;
}

export type AttemptStatus = typeof AttemptStatus[keyof typeof AttemptStatus];


export const AttemptStatus = {
  in_progress: 'in_progress',
  completed: 'completed',
  expired: 'expired',
  abandoned: 'abandoned',
} as const;

export interface AttemptResponse {
  id: number;
  test_id: number;
  user_id: number;
  status: AttemptStatus;
  started_at: string;
  finished_at: string | null;
  expires_at: string | null;
  score: number | null;
  max_score: number | null;
}

export interface AttemptResultResponse {
  attempt_id: number;
  test_id: number;
  test_title: string;
  status: AttemptStatus;
  score: number;
  max_score: number;
  started_at: string;
  finished_at: string | null;
  expires_at: string | null;
  answers?: AttemptAnswerDetail[];
}

export interface AttemptStartRequest {
  test_id: number;
}

export interface AuthorStatsResponse {
  total_tests: number;
  public_tests: number;
  total_attempts_received: number;
  completed_attempts_received: number;
}

export interface BodyUploadMediaApiV1MediaUploadPost {
  file: Blob;
}

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface LoginRequest {
  username_or_email: string;
  password: string;
}

export interface OptionAuthorResponse {
  id: number;
  text: string;
  order_number: number;
  is_correct: boolean;
}

export interface OptionCreate {
  /** @minLength 1 */
  text: string;
  is_correct?: boolean;
  /** @minimum 0 */
  order_number?: number;
}

export interface OptionResponse {
  id: number;
  text: string;
  order_number: number;
}

export interface QuestionAuthorResponse {
  id: number;
  question_type: QuestionType;
  text: string;
  order_number: number;
  points: number;
  explanation: string | null;
  correct_answer: string | null;
  image_url: string | null;
  options?: OptionAuthorResponse[];
}

export interface QuestionCreate {
  question_type: QuestionType;
  /** @minLength 1 */
  text: string;
  /** @minimum 0 */
  order_number?: number;
  /** @minimum 1 */
  points?: number;
  explanation?: string | null;
  correct_answer?: string | null;
  image_url?: string | null;
  options?: OptionCreate[];
}

export interface QuestionResponse {
  id: number;
  question_type: QuestionType;
  text: string;
  order_number: number;
  points: number;
  image_url: string | null;
  options?: OptionResponse[];
}

export interface QuestionUpdate {
  question_type?: QuestionType | null;
  text?: string | null;
  order_number?: number | null;
  points?: number | null;
  explanation?: string | null;
  correct_answer?: string | null;
  image_url?: string | null;
  options?: OptionCreate[] | null;
}

export interface TagCreate {
  /**
     * @minLength 1
     * @maxLength 100
     */
  name: string;
}

export interface TagResponse {
  id: number;
  name: string;
  slug: string;
}

export interface TestAuthorDetailResponse {
  id: number;
  author_id: number;
  title: string;
  description: string | null;
  is_public: boolean;
  time_limit_minutes: number | null;
  questions_count?: number;
  tags?: TagResponse[];
  created_at: string;
  updated_at: string;
  questions?: QuestionAuthorResponse[];
}

export interface TestCreate {
  /**
     * @minLength 1
     * @maxLength 255
     */
  title: string;
  description?: string | null;
  is_public?: boolean;
  time_limit_minutes?: number | null;
  tag_names?: string[];
}

export interface TestDetailResponse {
  id: number;
  author_id: number;
  title: string;
  description: string | null;
  is_public: boolean;
  time_limit_minutes: number | null;
  questions_count?: number;
  tags?: TagResponse[];
  created_at: string;
  updated_at: string;
  questions?: QuestionResponse[];
}

export interface TestResponse {
  id: number;
  author_id: number;
  title: string;
  description: string | null;
  is_public: boolean;
  time_limit_minutes: number | null;
  questions_count?: number;
  tags?: TagResponse[];
  created_at: string;
  updated_at: string;
}

export interface TestStatsResponse {
  test_id: number;
  test_title: string;
  total_attempts: number;
  completed_attempts: number;
  avg_score: number | null;
  avg_score_percent: number | null;
}

export interface TestUpdate {
  title?: string | null;
  description?: string | null;
  is_public?: boolean | null;
  time_limit_minutes?: number | null;
  tag_names?: string[] | null;
}

export interface UserResponse {
  id: number;
  email: string;
  first_name: string;
  last_name: string;
  middle_name?: string | null;
  username?: string | null;
  full_name?: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface TokenResponse {
  access_token: string;
  token_type?: string;
  user: UserResponse;
}

export interface UserCreate {
  email: string;
  /**
     * @minLength 1
     * @maxLength 100
     */
  first_name: string;
  /**
     * @minLength 1
     * @maxLength 100
     */
  last_name: string;
  middle_name?: string | null;
  avatar_url?: string | null;
  username?: string | null;
  full_name?: string | null;
  /**
     * @minLength 8
     * @maxLength 128
     */
  password: string;
}

export type ErrorBodyMeta = { [key: string]: unknown };

export interface ErrorBody {
  code: string;
  message: string;
  meta?: ErrorBodyMeta;
}

export interface ErrorResponse {
  error: ErrorBody;
  request_id: string;
}

export type HealthCheckApiV1HealthGet200 = { [key: string]: unknown };

export type PingApiV1PingGet200 = {[key: string]: string};

export type ListMyTestsApiV1TestsGetParams = {
skip?: number;
limit?: number;
};

export type SearchCatalogApiV1CatalogGetParams = {
q?: string | null;
tags?: string[];
skip?: number;
limit?: number;
};

export type UploadMediaApiV1MediaUploadPost201 = {[key: string]: string};

export type RootGet200 = { [key: string]: unknown };

