/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Test Constructor API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  HTTPValidationError,
  ListMyTestsApiV1TestsGetParams,
  QuestionAuthorResponse,
  QuestionCreate,
  QuestionUpdate,
  TestAuthorDetailResponse,
  TestCreate,
  TestDetailResponse,
  TestResponse,
  TestUpdate
} from './testConstructorAPI.schemas';

import { request } from '../axios';





export type createTestApiV1TestsPostResponse201 = {
  data: TestResponse
  status: 201
}

export type createTestApiV1TestsPostResponse400 = {
  data: ErrorResponse
  status: 400
}

export type createTestApiV1TestsPostResponse401 = {
  data: ErrorResponse
  status: 401
}

export type createTestApiV1TestsPostResponse403 = {
  data: ErrorResponse
  status: 403
}

export type createTestApiV1TestsPostResponse404 = {
  data: ErrorResponse
  status: 404
}

export type createTestApiV1TestsPostResponse409 = {
  data: ErrorResponse
  status: 409
}

export type createTestApiV1TestsPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createTestApiV1TestsPostResponse500 = {
  data: ErrorResponse
  status: 500
}

export type createTestApiV1TestsPostResponseSuccess = (createTestApiV1TestsPostResponse201) & {
  headers: Headers;
};
export type createTestApiV1TestsPostResponseError = (createTestApiV1TestsPostResponse400 | createTestApiV1TestsPostResponse401 | createTestApiV1TestsPostResponse403 | createTestApiV1TestsPostResponse404 | createTestApiV1TestsPostResponse409 | createTestApiV1TestsPostResponse422 | createTestApiV1TestsPostResponse500) & {
  headers: Headers;
};

export type createTestApiV1TestsPostResponse = (createTestApiV1TestsPostResponseSuccess | createTestApiV1TestsPostResponseError)

export const getCreateTestApiV1TestsPostUrl = () => {




  return `/api/v1/tests/`
}

/**
 * @summary Create Test
 */
export const createTestApiV1TestsPost = async (testCreate: TestCreate, options?: RequestInit): Promise<createTestApiV1TestsPostResponse> => {

  return request<createTestApiV1TestsPostResponse>(getCreateTestApiV1TestsPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(testCreate)
  }
);}





export const getCreateTestApiV1TestsPostQueryKey = (testCreate?: TestCreate,) => {
    return [
    'POST', `/api/v1/tests/`, testCreate
    ] as const;
    }


export const getCreateTestApiV1TestsPostQueryOptions = <TData = Awaited<ReturnType<typeof createTestApiV1TestsPost>>, TError = ErrorResponse | HTTPValidationError>(testCreate: TestCreate, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof createTestApiV1TestsPost>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCreateTestApiV1TestsPostQueryKey(testCreate);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof createTestApiV1TestsPost>>> = ({ signal }) => createTestApiV1TestsPost(testCreate, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof createTestApiV1TestsPost>>, TError, TData> & { queryKey: QueryKey }
}

export type CreateTestApiV1TestsPostQueryResult = NonNullable<Awaited<ReturnType<typeof createTestApiV1TestsPost>>>
export type CreateTestApiV1TestsPostQueryError = ErrorResponse | HTTPValidationError


/**
 * @summary Create Test
 */

export function useCreateTestApiV1TestsPost<TData = Awaited<ReturnType<typeof createTestApiV1TestsPost>>, TError = ErrorResponse | HTTPValidationError>(
 testCreate: TestCreate, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof createTestApiV1TestsPost>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getCreateTestApiV1TestsPostQueryOptions(testCreate,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type listMyTestsApiV1TestsGetResponse200 = {
  data: TestResponse[]
  status: 200
}

export type listMyTestsApiV1TestsGetResponse400 = {
  data: ErrorResponse
  status: 400
}

export type listMyTestsApiV1TestsGetResponse401 = {
  data: ErrorResponse
  status: 401
}

export type listMyTestsApiV1TestsGetResponse403 = {
  data: ErrorResponse
  status: 403
}

export type listMyTestsApiV1TestsGetResponse404 = {
  data: ErrorResponse
  status: 404
}

export type listMyTestsApiV1TestsGetResponse409 = {
  data: ErrorResponse
  status: 409
}

export type listMyTestsApiV1TestsGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listMyTestsApiV1TestsGetResponse500 = {
  data: ErrorResponse
  status: 500
}

export type listMyTestsApiV1TestsGetResponseSuccess = (listMyTestsApiV1TestsGetResponse200) & {
  headers: Headers;
};
export type listMyTestsApiV1TestsGetResponseError = (listMyTestsApiV1TestsGetResponse400 | listMyTestsApiV1TestsGetResponse401 | listMyTestsApiV1TestsGetResponse403 | listMyTestsApiV1TestsGetResponse404 | listMyTestsApiV1TestsGetResponse409 | listMyTestsApiV1TestsGetResponse422 | listMyTestsApiV1TestsGetResponse500) & {
  headers: Headers;
};

export type listMyTestsApiV1TestsGetResponse = (listMyTestsApiV1TestsGetResponseSuccess | listMyTestsApiV1TestsGetResponseError)

export const getListMyTestsApiV1TestsGetUrl = (params?: ListMyTestsApiV1TestsGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/tests/?${stringifiedParams}` : `/api/v1/tests/`
}

/**
 * @summary List My Tests
 */
export const listMyTestsApiV1TestsGet = async (params?: ListMyTestsApiV1TestsGetParams, options?: RequestInit): Promise<listMyTestsApiV1TestsGetResponse> => {

  return request<listMyTestsApiV1TestsGetResponse>(getListMyTestsApiV1TestsGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListMyTestsApiV1TestsGetQueryKey = (params?: ListMyTestsApiV1TestsGetParams,) => {
    return [
    `/api/v1/tests/`, ...(params ? [params] : [])
    ] as const;
    }


export const getListMyTestsApiV1TestsGetQueryOptions = <TData = Awaited<ReturnType<typeof listMyTestsApiV1TestsGet>>, TError = ErrorResponse | HTTPValidationError>(params?: ListMyTestsApiV1TestsGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listMyTestsApiV1TestsGet>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListMyTestsApiV1TestsGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listMyTestsApiV1TestsGet>>> = ({ signal }) => listMyTestsApiV1TestsGet(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listMyTestsApiV1TestsGet>>, TError, TData> & { queryKey: QueryKey }
}

export type ListMyTestsApiV1TestsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listMyTestsApiV1TestsGet>>>
export type ListMyTestsApiV1TestsGetQueryError = ErrorResponse | HTTPValidationError


/**
 * @summary List My Tests
 */

export function useListMyTestsApiV1TestsGet<TData = Awaited<ReturnType<typeof listMyTestsApiV1TestsGet>>, TError = ErrorResponse | HTTPValidationError>(
 params?: ListMyTestsApiV1TestsGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listMyTestsApiV1TestsGet>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListMyTestsApiV1TestsGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type getTestApiV1TestsTestIdGetResponse200 = {
  data: TestAuthorDetailResponse | TestDetailResponse
  status: 200
}

export type getTestApiV1TestsTestIdGetResponse400 = {
  data: ErrorResponse
  status: 400
}

export type getTestApiV1TestsTestIdGetResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getTestApiV1TestsTestIdGetResponse403 = {
  data: ErrorResponse
  status: 403
}

export type getTestApiV1TestsTestIdGetResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getTestApiV1TestsTestIdGetResponse409 = {
  data: ErrorResponse
  status: 409
}

export type getTestApiV1TestsTestIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getTestApiV1TestsTestIdGetResponse500 = {
  data: ErrorResponse
  status: 500
}

export type getTestApiV1TestsTestIdGetResponseSuccess = (getTestApiV1TestsTestIdGetResponse200) & {
  headers: Headers;
};
export type getTestApiV1TestsTestIdGetResponseError = (getTestApiV1TestsTestIdGetResponse400 | getTestApiV1TestsTestIdGetResponse401 | getTestApiV1TestsTestIdGetResponse403 | getTestApiV1TestsTestIdGetResponse404 | getTestApiV1TestsTestIdGetResponse409 | getTestApiV1TestsTestIdGetResponse422 | getTestApiV1TestsTestIdGetResponse500) & {
  headers: Headers;
};

export type getTestApiV1TestsTestIdGetResponse = (getTestApiV1TestsTestIdGetResponseSuccess | getTestApiV1TestsTestIdGetResponseError)

export const getGetTestApiV1TestsTestIdGetUrl = (testId: number,) => {




  return `/api/v1/tests/${testId}`
}

/**
 * @summary Get Test
 */
export const getTestApiV1TestsTestIdGet = async (testId: number, options?: RequestInit): Promise<getTestApiV1TestsTestIdGetResponse> => {

  return request<getTestApiV1TestsTestIdGetResponse>(getGetTestApiV1TestsTestIdGetUrl(testId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetTestApiV1TestsTestIdGetQueryKey = (testId: number,) => {
    return [
    `/api/v1/tests/${testId}`
    ] as const;
    }


export const getGetTestApiV1TestsTestIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getTestApiV1TestsTestIdGet>>, TError = ErrorResponse | HTTPValidationError>(testId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTestApiV1TestsTestIdGet>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTestApiV1TestsTestIdGetQueryKey(testId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTestApiV1TestsTestIdGet>>> = ({ signal }) => getTestApiV1TestsTestIdGet(testId, { signal });





   return  { queryKey, queryFn, enabled: testId !== null && testId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTestApiV1TestsTestIdGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetTestApiV1TestsTestIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getTestApiV1TestsTestIdGet>>>
export type GetTestApiV1TestsTestIdGetQueryError = ErrorResponse | HTTPValidationError


/**
 * @summary Get Test
 */

export function useGetTestApiV1TestsTestIdGet<TData = Awaited<ReturnType<typeof getTestApiV1TestsTestIdGet>>, TError = ErrorResponse | HTTPValidationError>(
 testId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTestApiV1TestsTestIdGet>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetTestApiV1TestsTestIdGetQueryOptions(testId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type updateTestApiV1TestsTestIdPatchResponse200 = {
  data: TestResponse
  status: 200
}

export type updateTestApiV1TestsTestIdPatchResponse400 = {
  data: ErrorResponse
  status: 400
}

export type updateTestApiV1TestsTestIdPatchResponse401 = {
  data: ErrorResponse
  status: 401
}

export type updateTestApiV1TestsTestIdPatchResponse403 = {
  data: ErrorResponse
  status: 403
}

export type updateTestApiV1TestsTestIdPatchResponse404 = {
  data: ErrorResponse
  status: 404
}

export type updateTestApiV1TestsTestIdPatchResponse409 = {
  data: ErrorResponse
  status: 409
}

export type updateTestApiV1TestsTestIdPatchResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type updateTestApiV1TestsTestIdPatchResponse500 = {
  data: ErrorResponse
  status: 500
}

export type updateTestApiV1TestsTestIdPatchResponseSuccess = (updateTestApiV1TestsTestIdPatchResponse200) & {
  headers: Headers;
};
export type updateTestApiV1TestsTestIdPatchResponseError = (updateTestApiV1TestsTestIdPatchResponse400 | updateTestApiV1TestsTestIdPatchResponse401 | updateTestApiV1TestsTestIdPatchResponse403 | updateTestApiV1TestsTestIdPatchResponse404 | updateTestApiV1TestsTestIdPatchResponse409 | updateTestApiV1TestsTestIdPatchResponse422 | updateTestApiV1TestsTestIdPatchResponse500) & {
  headers: Headers;
};

export type updateTestApiV1TestsTestIdPatchResponse = (updateTestApiV1TestsTestIdPatchResponseSuccess | updateTestApiV1TestsTestIdPatchResponseError)

export const getUpdateTestApiV1TestsTestIdPatchUrl = (testId: number,) => {




  return `/api/v1/tests/${testId}`
}

/**
 * @summary Update Test
 */
export const updateTestApiV1TestsTestIdPatch = async (testId: number,
    testUpdate: TestUpdate, options?: RequestInit): Promise<updateTestApiV1TestsTestIdPatchResponse> => {

  return request<updateTestApiV1TestsTestIdPatchResponse>(getUpdateTestApiV1TestsTestIdPatchUrl(testId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(testUpdate)
  }
);}





export const getUpdateTestApiV1TestsTestIdPatchQueryKey = (testId: number,
    testUpdate?: TestUpdate,) => {
    return [
    'PATCH', `/api/v1/tests/${testId}`, testUpdate
    ] as const;
    }


export const getUpdateTestApiV1TestsTestIdPatchQueryOptions = <TData = Awaited<ReturnType<typeof updateTestApiV1TestsTestIdPatch>>, TError = ErrorResponse | HTTPValidationError>(testId: number,
    testUpdate: TestUpdate, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof updateTestApiV1TestsTestIdPatch>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUpdateTestApiV1TestsTestIdPatchQueryKey(testId,testUpdate);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof updateTestApiV1TestsTestIdPatch>>> = ({ signal }) => updateTestApiV1TestsTestIdPatch(testId,testUpdate, { signal });





   return  { queryKey, queryFn, enabled: testId !== null && testId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof updateTestApiV1TestsTestIdPatch>>, TError, TData> & { queryKey: QueryKey }
}

export type UpdateTestApiV1TestsTestIdPatchQueryResult = NonNullable<Awaited<ReturnType<typeof updateTestApiV1TestsTestIdPatch>>>
export type UpdateTestApiV1TestsTestIdPatchQueryError = ErrorResponse | HTTPValidationError


/**
 * @summary Update Test
 */

export function useUpdateTestApiV1TestsTestIdPatch<TData = Awaited<ReturnType<typeof updateTestApiV1TestsTestIdPatch>>, TError = ErrorResponse | HTTPValidationError>(
 testId: number,
    testUpdate: TestUpdate, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof updateTestApiV1TestsTestIdPatch>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getUpdateTestApiV1TestsTestIdPatchQueryOptions(testId,testUpdate,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type deleteTestApiV1TestsTestIdDeleteResponse204 = {
  data: void
  status: 204
}

export type deleteTestApiV1TestsTestIdDeleteResponse400 = {
  data: ErrorResponse
  status: 400
}

export type deleteTestApiV1TestsTestIdDeleteResponse401 = {
  data: ErrorResponse
  status: 401
}

export type deleteTestApiV1TestsTestIdDeleteResponse403 = {
  data: ErrorResponse
  status: 403
}

export type deleteTestApiV1TestsTestIdDeleteResponse404 = {
  data: ErrorResponse
  status: 404
}

export type deleteTestApiV1TestsTestIdDeleteResponse409 = {
  data: ErrorResponse
  status: 409
}

export type deleteTestApiV1TestsTestIdDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type deleteTestApiV1TestsTestIdDeleteResponse500 = {
  data: ErrorResponse
  status: 500
}

export type deleteTestApiV1TestsTestIdDeleteResponseSuccess = (deleteTestApiV1TestsTestIdDeleteResponse204) & {
  headers: Headers;
};
export type deleteTestApiV1TestsTestIdDeleteResponseError = (deleteTestApiV1TestsTestIdDeleteResponse400 | deleteTestApiV1TestsTestIdDeleteResponse401 | deleteTestApiV1TestsTestIdDeleteResponse403 | deleteTestApiV1TestsTestIdDeleteResponse404 | deleteTestApiV1TestsTestIdDeleteResponse409 | deleteTestApiV1TestsTestIdDeleteResponse422 | deleteTestApiV1TestsTestIdDeleteResponse500) & {
  headers: Headers;
};

export type deleteTestApiV1TestsTestIdDeleteResponse = (deleteTestApiV1TestsTestIdDeleteResponseSuccess | deleteTestApiV1TestsTestIdDeleteResponseError)

export const getDeleteTestApiV1TestsTestIdDeleteUrl = (testId: number,) => {




  return `/api/v1/tests/${testId}`
}

/**
 * @summary Delete Test
 */
export const deleteTestApiV1TestsTestIdDelete = async (testId: number, options?: RequestInit): Promise<deleteTestApiV1TestsTestIdDeleteResponse> => {

  return request<deleteTestApiV1TestsTestIdDeleteResponse>(getDeleteTestApiV1TestsTestIdDeleteUrl(testId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteTestApiV1TestsTestIdDeleteQueryKey = (testId: number,) => {
    return [
    'DELETE', `/api/v1/tests/${testId}`
    ] as const;
    }


export const getDeleteTestApiV1TestsTestIdDeleteQueryOptions = <TData = Awaited<ReturnType<typeof deleteTestApiV1TestsTestIdDelete>>, TError = ErrorResponse | HTTPValidationError>(testId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof deleteTestApiV1TestsTestIdDelete>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDeleteTestApiV1TestsTestIdDeleteQueryKey(testId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof deleteTestApiV1TestsTestIdDelete>>> = ({ signal }) => deleteTestApiV1TestsTestIdDelete(testId, { signal });





   return  { queryKey, queryFn, enabled: testId !== null && testId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof deleteTestApiV1TestsTestIdDelete>>, TError, TData> & { queryKey: QueryKey }
}

export type DeleteTestApiV1TestsTestIdDeleteQueryResult = NonNullable<Awaited<ReturnType<typeof deleteTestApiV1TestsTestIdDelete>>>
export type DeleteTestApiV1TestsTestIdDeleteQueryError = ErrorResponse | HTTPValidationError


/**
 * @summary Delete Test
 */

export function useDeleteTestApiV1TestsTestIdDelete<TData = Awaited<ReturnType<typeof deleteTestApiV1TestsTestIdDelete>>, TError = ErrorResponse | HTTPValidationError>(
 testId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof deleteTestApiV1TestsTestIdDelete>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getDeleteTestApiV1TestsTestIdDeleteQueryOptions(testId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type addQuestionApiV1TestsTestIdQuestionsPostResponse201 = {
  data: QuestionAuthorResponse
  status: 201
}

export type addQuestionApiV1TestsTestIdQuestionsPostResponse400 = {
  data: ErrorResponse
  status: 400
}

export type addQuestionApiV1TestsTestIdQuestionsPostResponse401 = {
  data: ErrorResponse
  status: 401
}

export type addQuestionApiV1TestsTestIdQuestionsPostResponse403 = {
  data: ErrorResponse
  status: 403
}

export type addQuestionApiV1TestsTestIdQuestionsPostResponse404 = {
  data: ErrorResponse
  status: 404
}

export type addQuestionApiV1TestsTestIdQuestionsPostResponse409 = {
  data: ErrorResponse
  status: 409
}

export type addQuestionApiV1TestsTestIdQuestionsPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type addQuestionApiV1TestsTestIdQuestionsPostResponse500 = {
  data: ErrorResponse
  status: 500
}

export type addQuestionApiV1TestsTestIdQuestionsPostResponseSuccess = (addQuestionApiV1TestsTestIdQuestionsPostResponse201) & {
  headers: Headers;
};
export type addQuestionApiV1TestsTestIdQuestionsPostResponseError = (addQuestionApiV1TestsTestIdQuestionsPostResponse400 | addQuestionApiV1TestsTestIdQuestionsPostResponse401 | addQuestionApiV1TestsTestIdQuestionsPostResponse403 | addQuestionApiV1TestsTestIdQuestionsPostResponse404 | addQuestionApiV1TestsTestIdQuestionsPostResponse409 | addQuestionApiV1TestsTestIdQuestionsPostResponse422 | addQuestionApiV1TestsTestIdQuestionsPostResponse500) & {
  headers: Headers;
};

export type addQuestionApiV1TestsTestIdQuestionsPostResponse = (addQuestionApiV1TestsTestIdQuestionsPostResponseSuccess | addQuestionApiV1TestsTestIdQuestionsPostResponseError)

export const getAddQuestionApiV1TestsTestIdQuestionsPostUrl = (testId: number,) => {




  return `/api/v1/tests/${testId}/questions`
}

/**
 * @summary Add Question
 */
export const addQuestionApiV1TestsTestIdQuestionsPost = async (testId: number,
    questionCreate: QuestionCreate, options?: RequestInit): Promise<addQuestionApiV1TestsTestIdQuestionsPostResponse> => {

  return request<addQuestionApiV1TestsTestIdQuestionsPostResponse>(getAddQuestionApiV1TestsTestIdQuestionsPostUrl(testId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(questionCreate)
  }
);}





export const getAddQuestionApiV1TestsTestIdQuestionsPostQueryKey = (testId: number,
    questionCreate?: QuestionCreate,) => {
    return [
    'POST', `/api/v1/tests/${testId}/questions`, questionCreate
    ] as const;
    }


export const getAddQuestionApiV1TestsTestIdQuestionsPostQueryOptions = <TData = Awaited<ReturnType<typeof addQuestionApiV1TestsTestIdQuestionsPost>>, TError = ErrorResponse | HTTPValidationError>(testId: number,
    questionCreate: QuestionCreate, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof addQuestionApiV1TestsTestIdQuestionsPost>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAddQuestionApiV1TestsTestIdQuestionsPostQueryKey(testId,questionCreate);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof addQuestionApiV1TestsTestIdQuestionsPost>>> = ({ signal }) => addQuestionApiV1TestsTestIdQuestionsPost(testId,questionCreate, { signal });





   return  { queryKey, queryFn, enabled: testId !== null && testId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof addQuestionApiV1TestsTestIdQuestionsPost>>, TError, TData> & { queryKey: QueryKey }
}

export type AddQuestionApiV1TestsTestIdQuestionsPostQueryResult = NonNullable<Awaited<ReturnType<typeof addQuestionApiV1TestsTestIdQuestionsPost>>>
export type AddQuestionApiV1TestsTestIdQuestionsPostQueryError = ErrorResponse | HTTPValidationError


/**
 * @summary Add Question
 */

export function useAddQuestionApiV1TestsTestIdQuestionsPost<TData = Awaited<ReturnType<typeof addQuestionApiV1TestsTestIdQuestionsPost>>, TError = ErrorResponse | HTTPValidationError>(
 testId: number,
    questionCreate: QuestionCreate, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof addQuestionApiV1TestsTestIdQuestionsPost>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getAddQuestionApiV1TestsTestIdQuestionsPostQueryOptions(testId,questionCreate,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type updateQuestionApiV1TestsTestIdQuestionsQuestionIdPatchResponse200 = {
  data: QuestionAuthorResponse
  status: 200
}

export type updateQuestionApiV1TestsTestIdQuestionsQuestionIdPatchResponse400 = {
  data: ErrorResponse
  status: 400
}

export type updateQuestionApiV1TestsTestIdQuestionsQuestionIdPatchResponse401 = {
  data: ErrorResponse
  status: 401
}

export type updateQuestionApiV1TestsTestIdQuestionsQuestionIdPatchResponse403 = {
  data: ErrorResponse
  status: 403
}

export type updateQuestionApiV1TestsTestIdQuestionsQuestionIdPatchResponse404 = {
  data: ErrorResponse
  status: 404
}

export type updateQuestionApiV1TestsTestIdQuestionsQuestionIdPatchResponse409 = {
  data: ErrorResponse
  status: 409
}

export type updateQuestionApiV1TestsTestIdQuestionsQuestionIdPatchResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type updateQuestionApiV1TestsTestIdQuestionsQuestionIdPatchResponse500 = {
  data: ErrorResponse
  status: 500
}

export type updateQuestionApiV1TestsTestIdQuestionsQuestionIdPatchResponseSuccess = (updateQuestionApiV1TestsTestIdQuestionsQuestionIdPatchResponse200) & {
  headers: Headers;
};
export type updateQuestionApiV1TestsTestIdQuestionsQuestionIdPatchResponseError = (updateQuestionApiV1TestsTestIdQuestionsQuestionIdPatchResponse400 | updateQuestionApiV1TestsTestIdQuestionsQuestionIdPatchResponse401 | updateQuestionApiV1TestsTestIdQuestionsQuestionIdPatchResponse403 | updateQuestionApiV1TestsTestIdQuestionsQuestionIdPatchResponse404 | updateQuestionApiV1TestsTestIdQuestionsQuestionIdPatchResponse409 | updateQuestionApiV1TestsTestIdQuestionsQuestionIdPatchResponse422 | updateQuestionApiV1TestsTestIdQuestionsQuestionIdPatchResponse500) & {
  headers: Headers;
};

export type updateQuestionApiV1TestsTestIdQuestionsQuestionIdPatchResponse = (updateQuestionApiV1TestsTestIdQuestionsQuestionIdPatchResponseSuccess | updateQuestionApiV1TestsTestIdQuestionsQuestionIdPatchResponseError)

export const getUpdateQuestionApiV1TestsTestIdQuestionsQuestionIdPatchUrl = (testId: number,
    questionId: number,) => {




  return `/api/v1/tests/${testId}/questions/${questionId}`
}

/**
 * @summary Update Question
 */
export const updateQuestionApiV1TestsTestIdQuestionsQuestionIdPatch = async (testId: number,
    questionId: number,
    questionUpdate: QuestionUpdate, options?: RequestInit): Promise<updateQuestionApiV1TestsTestIdQuestionsQuestionIdPatchResponse> => {

  return request<updateQuestionApiV1TestsTestIdQuestionsQuestionIdPatchResponse>(getUpdateQuestionApiV1TestsTestIdQuestionsQuestionIdPatchUrl(testId,questionId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(questionUpdate)
  }
);}





export const getUpdateQuestionApiV1TestsTestIdQuestionsQuestionIdPatchQueryKey = (testId: number,
    questionId: number,
    questionUpdate?: QuestionUpdate,) => {
    return [
    'PATCH', `/api/v1/tests/${testId}/questions/${questionId}`, questionUpdate
    ] as const;
    }


export const getUpdateQuestionApiV1TestsTestIdQuestionsQuestionIdPatchQueryOptions = <TData = Awaited<ReturnType<typeof updateQuestionApiV1TestsTestIdQuestionsQuestionIdPatch>>, TError = ErrorResponse | HTTPValidationError>(testId: number,
    questionId: number,
    questionUpdate: QuestionUpdate, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof updateQuestionApiV1TestsTestIdQuestionsQuestionIdPatch>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUpdateQuestionApiV1TestsTestIdQuestionsQuestionIdPatchQueryKey(testId,questionId,questionUpdate);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof updateQuestionApiV1TestsTestIdQuestionsQuestionIdPatch>>> = ({ signal }) => updateQuestionApiV1TestsTestIdQuestionsQuestionIdPatch(testId,questionId,questionUpdate, { signal });





   return  { queryKey, queryFn, enabled: testId !== null && testId !== undefined && questionId !== null && questionId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof updateQuestionApiV1TestsTestIdQuestionsQuestionIdPatch>>, TError, TData> & { queryKey: QueryKey }
}

export type UpdateQuestionApiV1TestsTestIdQuestionsQuestionIdPatchQueryResult = NonNullable<Awaited<ReturnType<typeof updateQuestionApiV1TestsTestIdQuestionsQuestionIdPatch>>>
export type UpdateQuestionApiV1TestsTestIdQuestionsQuestionIdPatchQueryError = ErrorResponse | HTTPValidationError


/**
 * @summary Update Question
 */

export function useUpdateQuestionApiV1TestsTestIdQuestionsQuestionIdPatch<TData = Awaited<ReturnType<typeof updateQuestionApiV1TestsTestIdQuestionsQuestionIdPatch>>, TError = ErrorResponse | HTTPValidationError>(
 testId: number,
    questionId: number,
    questionUpdate: QuestionUpdate, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof updateQuestionApiV1TestsTestIdQuestionsQuestionIdPatch>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getUpdateQuestionApiV1TestsTestIdQuestionsQuestionIdPatchQueryOptions(testId,questionId,questionUpdate,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type deleteQuestionApiV1TestsTestIdQuestionsQuestionIdDeleteResponse204 = {
  data: void
  status: 204
}

export type deleteQuestionApiV1TestsTestIdQuestionsQuestionIdDeleteResponse400 = {
  data: ErrorResponse
  status: 400
}

export type deleteQuestionApiV1TestsTestIdQuestionsQuestionIdDeleteResponse401 = {
  data: ErrorResponse
  status: 401
}

export type deleteQuestionApiV1TestsTestIdQuestionsQuestionIdDeleteResponse403 = {
  data: ErrorResponse
  status: 403
}

export type deleteQuestionApiV1TestsTestIdQuestionsQuestionIdDeleteResponse404 = {
  data: ErrorResponse
  status: 404
}

export type deleteQuestionApiV1TestsTestIdQuestionsQuestionIdDeleteResponse409 = {
  data: ErrorResponse
  status: 409
}

export type deleteQuestionApiV1TestsTestIdQuestionsQuestionIdDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type deleteQuestionApiV1TestsTestIdQuestionsQuestionIdDeleteResponse500 = {
  data: ErrorResponse
  status: 500
}

export type deleteQuestionApiV1TestsTestIdQuestionsQuestionIdDeleteResponseSuccess = (deleteQuestionApiV1TestsTestIdQuestionsQuestionIdDeleteResponse204) & {
  headers: Headers;
};
export type deleteQuestionApiV1TestsTestIdQuestionsQuestionIdDeleteResponseError = (deleteQuestionApiV1TestsTestIdQuestionsQuestionIdDeleteResponse400 | deleteQuestionApiV1TestsTestIdQuestionsQuestionIdDeleteResponse401 | deleteQuestionApiV1TestsTestIdQuestionsQuestionIdDeleteResponse403 | deleteQuestionApiV1TestsTestIdQuestionsQuestionIdDeleteResponse404 | deleteQuestionApiV1TestsTestIdQuestionsQuestionIdDeleteResponse409 | deleteQuestionApiV1TestsTestIdQuestionsQuestionIdDeleteResponse422 | deleteQuestionApiV1TestsTestIdQuestionsQuestionIdDeleteResponse500) & {
  headers: Headers;
};

export type deleteQuestionApiV1TestsTestIdQuestionsQuestionIdDeleteResponse = (deleteQuestionApiV1TestsTestIdQuestionsQuestionIdDeleteResponseSuccess | deleteQuestionApiV1TestsTestIdQuestionsQuestionIdDeleteResponseError)

export const getDeleteQuestionApiV1TestsTestIdQuestionsQuestionIdDeleteUrl = (testId: number,
    questionId: number,) => {




  return `/api/v1/tests/${testId}/questions/${questionId}`
}

/**
 * @summary Delete Question
 */
export const deleteQuestionApiV1TestsTestIdQuestionsQuestionIdDelete = async (testId: number,
    questionId: number, options?: RequestInit): Promise<deleteQuestionApiV1TestsTestIdQuestionsQuestionIdDeleteResponse> => {

  return request<deleteQuestionApiV1TestsTestIdQuestionsQuestionIdDeleteResponse>(getDeleteQuestionApiV1TestsTestIdQuestionsQuestionIdDeleteUrl(testId,questionId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteQuestionApiV1TestsTestIdQuestionsQuestionIdDeleteQueryKey = (testId: number,
    questionId: number,) => {
    return [
    'DELETE', `/api/v1/tests/${testId}/questions/${questionId}`
    ] as const;
    }


export const getDeleteQuestionApiV1TestsTestIdQuestionsQuestionIdDeleteQueryOptions = <TData = Awaited<ReturnType<typeof deleteQuestionApiV1TestsTestIdQuestionsQuestionIdDelete>>, TError = ErrorResponse | HTTPValidationError>(testId: number,
    questionId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof deleteQuestionApiV1TestsTestIdQuestionsQuestionIdDelete>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDeleteQuestionApiV1TestsTestIdQuestionsQuestionIdDeleteQueryKey(testId,questionId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof deleteQuestionApiV1TestsTestIdQuestionsQuestionIdDelete>>> = ({ signal }) => deleteQuestionApiV1TestsTestIdQuestionsQuestionIdDelete(testId,questionId, { signal });





   return  { queryKey, queryFn, enabled: testId !== null && testId !== undefined && questionId !== null && questionId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof deleteQuestionApiV1TestsTestIdQuestionsQuestionIdDelete>>, TError, TData> & { queryKey: QueryKey }
}

export type DeleteQuestionApiV1TestsTestIdQuestionsQuestionIdDeleteQueryResult = NonNullable<Awaited<ReturnType<typeof deleteQuestionApiV1TestsTestIdQuestionsQuestionIdDelete>>>
export type DeleteQuestionApiV1TestsTestIdQuestionsQuestionIdDeleteQueryError = ErrorResponse | HTTPValidationError


/**
 * @summary Delete Question
 */

export function useDeleteQuestionApiV1TestsTestIdQuestionsQuestionIdDelete<TData = Awaited<ReturnType<typeof deleteQuestionApiV1TestsTestIdQuestionsQuestionIdDelete>>, TError = ErrorResponse | HTTPValidationError>(
 testId: number,
    questionId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof deleteQuestionApiV1TestsTestIdQuestionsQuestionIdDelete>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getDeleteQuestionApiV1TestsTestIdQuestionsQuestionIdDeleteQueryOptions(testId,questionId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






